//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.WCF.ServiceLayer.SocialMediaServiceOfflineReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SocialMediaServiceOfflineReference.ISocialMediaServiceOffline")]
    public interface ISocialMediaServiceOffline {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialMediaServiceOffline/PublishToFacebook", ReplyAction="http://tempuri.org/ISocialMediaServiceOffline/PublishToFacebookResponse")]
        bool PublishToFacebook(string post, byte[] imageBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialMediaServiceOffline/PublishToFacebook", ReplyAction="http://tempuri.org/ISocialMediaServiceOffline/PublishToFacebookResponse")]
        System.Threading.Tasks.Task<bool> PublishToFacebookAsync(string post, byte[] imageBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialMediaServiceOffline/PublishToTwitter", ReplyAction="http://tempuri.org/ISocialMediaServiceOffline/PublishToTwitterResponse")]
        bool PublishToTwitter(string post, byte[] imageBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialMediaServiceOffline/PublishToTwitter", ReplyAction="http://tempuri.org/ISocialMediaServiceOffline/PublishToTwitterResponse")]
        System.Threading.Tasks.Task<bool> PublishToTwitterAsync(string post, byte[] imageBytes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocialMediaServiceOfflineChannel : STC.Projects.WCF.ServiceLayer.SocialMediaServiceOfflineReference.ISocialMediaServiceOffline, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocialMediaServiceOfflineClient : System.ServiceModel.ClientBase<STC.Projects.WCF.ServiceLayer.SocialMediaServiceOfflineReference.ISocialMediaServiceOffline>, STC.Projects.WCF.ServiceLayer.SocialMediaServiceOfflineReference.ISocialMediaServiceOffline {
        
        public SocialMediaServiceOfflineClient() {
        }
        
        public SocialMediaServiceOfflineClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocialMediaServiceOfflineClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialMediaServiceOfflineClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialMediaServiceOfflineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PublishToFacebook(string post, byte[] imageBytes) {
            return base.Channel.PublishToFacebook(post, imageBytes);
        }
        
        public System.Threading.Tasks.Task<bool> PublishToFacebookAsync(string post, byte[] imageBytes) {
            return base.Channel.PublishToFacebookAsync(post, imageBytes);
        }
        
        public bool PublishToTwitter(string post, byte[] imageBytes) {
            return base.Channel.PublishToTwitter(post, imageBytes);
        }
        
        public System.Threading.Tasks.Task<bool> PublishToTwitterAsync(string post, byte[] imageBytes) {
            return base.Channel.PublishToTwitterAsync(post, imageBytes);
        }
    }
}
