//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.WPFControlLibrary.LandingPage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STC.Projects.WPFControlLibrary.LandingPage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCIDENTS.
        /// </summary>
        public static string strAccidents {
            get {
                return ResourceManager.GetString("strAccidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents Count Daily.
        /// </summary>
        public static string strAccidentsCountDaily {
            get {
                return ResourceManager.GetString("strAccidentsCountDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents Count Monthly.
        /// </summary>
        public static string strAccidentsCountMonthly {
            get {
                return ResourceManager.GetString("strAccidentsCountMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents Count Weekly.
        /// </summary>
        public static string strAccidentsCountWeekly {
            get {
                return ResourceManager.GetString("strAccidentsCountWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents Count Yearly.
        /// </summary>
        public static string strAccidentsCountYearly {
            get {
                return ResourceManager.GetString("strAccidentsCountYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents Count Comparision with Daily.
        /// </summary>
        public static string strAccidentsDailyStatis {
            get {
                return ResourceManager.GetString("strAccidentsDailyStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents Daily Trend.
        /// </summary>
        public static string strAccidentsDailyTrend {
            get {
                return ResourceManager.GetString("strAccidentsDailyTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents Count Comparision with Monthly.
        /// </summary>
        public static string strAccidentsMonthsStatis {
            get {
                return ResourceManager.GetString("strAccidentsMonthsStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents Monthly Trend.
        /// </summary>
        public static string strAccidentsMonthTrend {
            get {
                return ResourceManager.GetString("strAccidentsMonthTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents Quarterly Trend.
        /// </summary>
        public static string strAccidentsQtrTrend {
            get {
                return ResourceManager.GetString("strAccidentsQtrTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents Weekly Trend.
        /// </summary>
        public static string strAccidentsWeeklyTrend {
            get {
                return ResourceManager.GetString("strAccidentsWeeklyTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents Count Comparision with Weekly.
        /// </summary>
        public static string strAccidentsWeekStatis {
            get {
                return ResourceManager.GetString("strAccidentsWeekStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents Count Comparision with Yearly .
        /// </summary>
        public static string strAccidentsYearStatis {
            get {
                return ResourceManager.GetString("strAccidentsYearStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Percentage.
        /// </summary>
        public static string strActualPercentage {
            get {
                return ResourceManager.GetString("strActualPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALYSIS.
        /// </summary>
        public static string strAnalysis {
            get {
                return ResourceManager.GetString("strAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string strand {
            get {
                return ResourceManager.GetString("strand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Comparision.
        /// </summary>
        public static string strByComparison {
            get {
                return ResourceManager.GetString("strByComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Type.
        /// </summary>
        public static string strByType {
            get {
                return ResourceManager.GetString("strByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Value.
        /// </summary>
        public static string strCurrentValue {
            get {
                return ResourceManager.GetString("strCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Violations Daily Trend.
        /// </summary>
        public static string strDangerousViolationsDailyTrend {
            get {
                return ResourceManager.GetString("strDangerousViolationsDailyTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Violations Weekly Trend.
        /// </summary>
        public static string strDangerousViolationsWeeklyTrend {
            get {
                return ResourceManager.GetString("strDangerousViolationsWeeklyTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANGEROUS VIOLATOR.
        /// </summary>
        public static string strDangerousViolator {
            get {
                return ResourceManager.GetString("strDangerousViolator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Violations Monthly Trend.
        /// </summary>
        public static string strDangerousVoilationsMonthTrend {
            get {
                return ResourceManager.GetString("strDangerousVoilationsMonthTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Violation Quarterly Trend.
        /// </summary>
        public static string strDangerViolationQtrTrend {
            get {
                return ResourceManager.GetString("strDangerViolationQtrTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangererous Violations Count Daily.
        /// </summary>
        public static string strDangerViolationsCountDaily {
            get {
                return ResourceManager.GetString("strDangerViolationsCountDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangererous Violations Count Monthly.
        /// </summary>
        public static string strDangerViolationsCountMonthly {
            get {
                return ResourceManager.GetString("strDangerViolationsCountMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangererous Violations Count Weekly.
        /// </summary>
        public static string strDangerViolationsCountWeekly {
            get {
                return ResourceManager.GetString("strDangerViolationsCountWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangererous Violations Count Yearly.
        /// </summary>
        public static string strDangerViolationsCountYearly {
            get {
                return ResourceManager.GetString("strDangerViolationsCountYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Violations Count Comparision with Daily.
        /// </summary>
        public static string strDangViolnDailyStatis {
            get {
                return ResourceManager.GetString("strDangViolnDailyStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Violations Count Comparision with Monthly.
        /// </summary>
        public static string strDangViolnMonthsStatis {
            get {
                return ResourceManager.GetString("strDangViolnMonthsStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Violations Count Comparision with Weekly.
        /// </summary>
        public static string strDangViolnWeekStatis {
            get {
                return ResourceManager.GetString("strDangViolnWeekStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Violations Count Comparision with Yearly .
        /// </summary>
        public static string strDangViolnYearStatis {
            get {
                return ResourceManager.GetString("strDangViolnYearStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        public static string strDashboard {
            get {
                return ResourceManager.GetString("strDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatality Target by 2030.
        /// </summary>
        public static string strFatality {
            get {
                return ResourceManager.GetString("strFatality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORECAST.
        /// </summary>
        public static string strForeCast {
            get {
                return ResourceManager.GetString("strForeCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string strFrom {
            get {
                return ResourceManager.GetString("strFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAL.
        /// </summary>
        public static string strGeneral {
            get {
                return ResourceManager.GetString("strGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEAT MAPS.
        /// </summary>
        public static string strHeatMap {
            get {
                return ResourceManager.GetString("strHeatMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Day.
        /// </summary>
        public static string strHighestDay {
            get {
                return ResourceManager.GetString("strHighestDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Month.
        /// </summary>
        public static string strHighestMonth {
            get {
                return ResourceManager.GetString("strHighestMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Quarter.
        /// </summary>
        public static string strHighestQuarter {
            get {
                return ResourceManager.GetString("strHighestQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Week.
        /// </summary>
        public static string strHighestWeek {
            get {
                return ResourceManager.GetString("strHighestWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string strHome {
            get {
                return ResourceManager.GetString("strHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents Reasons Comparison.
        /// </summary>
        public static string strIncidentsReasons {
            get {
                return ResourceManager.GetString("strIncidentsReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI Name.
        /// </summary>
        public static string strKPIName {
            get {
                return ResourceManager.GetString("strKPIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPIs Table Chart.
        /// </summary>
        public static string strKPITableChart {
            get {
                return ResourceManager.GetString("strKPITableChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI&apos;s TABLE CHARTS.
        /// </summary>
        public static string strKPITableCharts {
            get {
                return ResourceManager.GetString("strKPITableCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents Comparison with.
        /// </summary>
        public static string strMainAccidentsYearRegion {
            get {
                return ResourceManager.GetString("strMainAccidentsYearRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents Count.
        /// </summary>
        public static string strMainIncidentsCount {
            get {
                return ResourceManager.GetString("strMainIncidentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Comparison With.
        /// </summary>
        public static string strMainViolationsComparisonYearly {
            get {
                return ResourceManager.GetString("strMainViolationsComparisonYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count.
        /// </summary>
        public static string strMainViolationsCount {
            get {
                return ResourceManager.GetString("strMainViolationsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANUAL KPI.
        /// </summary>
        public static string strManualKPI {
            get {
                return ResourceManager.GetString("strManualKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of accident with fatality.
        /// </summary>
        public static string strNoofaccidentwithfatality {
            get {
                return ResourceManager.GetString("strNoofaccidentwithfatality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of  Dangerous Violations.
        /// </summary>
        public static string strNoofDangerousViolations {
            get {
                return ResourceManager.GetString("strNoofDangerousViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Fatalities.
        /// </summary>
        public static string strNoOfFatalities {
            get {
                return ResourceManager.GetString("strNoOfFatalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Injuries.
        /// </summary>
        public static string strNoOfinjuries {
            get {
                return ResourceManager.GetString("strNoOfinjuries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Severe Accident.
        /// </summary>
        public static string strNoSevereAccident {
            get {
                return ResourceManager.GetString("strNoSevereAccident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERVIEW.
        /// </summary>
        public static string strOverview {
            get {
                return ResourceManager.GetString("strOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATROL CAR.
        /// </summary>
        public static string strPatrolCar {
            get {
                return ResourceManager.GetString("strPatrolCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string strPercentage {
            get {
                return ResourceManager.GetString("strPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERFORMANCE.
        /// </summary>
        public static string strPerformance {
            get {
                return ResourceManager.GetString("strPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREDICTION.
        /// </summary>
        public static string strPrediction {
            get {
                return ResourceManager.GetString("strPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Value.
        /// </summary>
        public static string strPreviousValue {
            get {
                return ResourceManager.GetString("strPreviousValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATISTICS.
        /// </summary>
        public static string strStatistics {
            get {
                return ResourceManager.GetString("strStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATISTICS ANALYSIS.
        /// </summary>
        public static string strStatisticsAnalysis {
            get {
                return ResourceManager.GetString("strStatisticsAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARGETS.
        /// </summary>
        public static string strTargets {
            get {
                return ResourceManager.GetString("strTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Value.
        /// </summary>
        public static string strTargetValue {
            get {
                return ResourceManager.GetString("strTargetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string strTo {
            get {
                return ResourceManager.GetString("strTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Violations Count Comparison With Daily.
        /// </summary>
        public static string strTrcukViolationsComparisonDaily {
            get {
                return ResourceManager.GetString("strTrcukViolationsComparisonDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Violations Count Comparison With Monthly.
        /// </summary>
        public static string strTrcukViolationsComparisonMonthly {
            get {
                return ResourceManager.GetString("strTrcukViolationsComparisonMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Violations Count Comparison With Weekly.
        /// </summary>
        public static string strTrcukViolationsComparisonWeekly {
            get {
                return ResourceManager.GetString("strTrcukViolationsComparisonWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Violations Count Comparison With Yearly.
        /// </summary>
        public static string strTrcukViolationsComparisonYearly {
            get {
                return ResourceManager.GetString("strTrcukViolationsComparisonYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TREND ANALYSIS.
        /// </summary>
        public static string strTrendAnalysis {
            get {
                return ResourceManager.GetString("strTrendAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Violation Daily Trend.
        /// </summary>
        public static string strTruckPermissionDailyTrend {
            get {
                return ResourceManager.GetString("strTruckPermissionDailyTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Violation Monthly Trend.
        /// </summary>
        public static string strTruckPermissionMonthTrend {
            get {
                return ResourceManager.GetString("strTruckPermissionMonthTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Violation Quarterly Trend.
        /// </summary>
        public static string strTruckPermissionQtrTrend {
            get {
                return ResourceManager.GetString("strTruckPermissionQtrTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUCK PERMISSIONS.
        /// </summary>
        public static string strTruckPermissions {
            get {
                return ResourceManager.GetString("strTruckPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Violation Weekly Trend.
        /// </summary>
        public static string strTruckPermissionWeeklyTrend {
            get {
                return ResourceManager.GetString("strTruckPermissionWeeklyTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Violations Count Daily.
        /// </summary>
        public static string strTruckViolationsCountDaily {
            get {
                return ResourceManager.GetString("strTruckViolationsCountDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Violations Count Monthly.
        /// </summary>
        public static string strTruckViolationsCountMonthly {
            get {
                return ResourceManager.GetString("strTruckViolationsCountMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Violations Count Weekly.
        /// </summary>
        public static string strTruckViolationsCountWeekly {
            get {
                return ResourceManager.GetString("strTruckViolationsCountWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Violations Count Yearly.
        /// </summary>
        public static string strTruckViolationsCountYearly {
            get {
                return ResourceManager.GetString("strTruckViolationsCountYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string strValue {
            get {
                return ResourceManager.GetString("strValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation Quarterly Trend.
        /// </summary>
        public static string strViolationQtrTrend {
            get {
                return ResourceManager.GetString("strViolationQtrTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIOLATIONS.
        /// </summary>
        public static string strViolations {
            get {
                return ResourceManager.GetString("strViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count Comparison With Daily.
        /// </summary>
        public static string strViolationsComparisonDaily {
            get {
                return ResourceManager.GetString("strViolationsComparisonDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count Comparison With Monthly.
        /// </summary>
        public static string strViolationsComparisonMonthly {
            get {
                return ResourceManager.GetString("strViolationsComparisonMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count Comparison With Weekly.
        /// </summary>
        public static string strViolationsComparisonWeekly {
            get {
                return ResourceManager.GetString("strViolationsComparisonWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count Comparison With Yearly.
        /// </summary>
        public static string strViolationsComparisonYearly {
            get {
                return ResourceManager.GetString("strViolationsComparisonYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count Daily.
        /// </summary>
        public static string strViolationsCountDaily {
            get {
                return ResourceManager.GetString("strViolationsCountDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count Monthly.
        /// </summary>
        public static string strViolationsCountMonthly {
            get {
                return ResourceManager.GetString("strViolationsCountMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count Weekly.
        /// </summary>
        public static string strViolationsCountWeekly {
            get {
                return ResourceManager.GetString("strViolationsCountWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count Yearly.
        /// </summary>
        public static string strViolationsCountYearly {
            get {
                return ResourceManager.GetString("strViolationsCountYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count by Region Comparision with Daily.
        /// </summary>
        public static string strViolationsDailyStatis {
            get {
                return ResourceManager.GetString("strViolationsDailyStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Daily Trend.
        /// </summary>
        public static string strViolationsDailyTrend {
            get {
                return ResourceManager.GetString("strViolationsDailyTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count by Region Comparision with Monthly.
        /// </summary>
        public static string strViolationsMonthsStatis {
            get {
                return ResourceManager.GetString("strViolationsMonthsStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Monthly Trend.
        /// </summary>
        public static string strViolationsMonthTrend {
            get {
                return ResourceManager.GetString("strViolationsMonthTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Weekly Trend.
        /// </summary>
        public static string strViolationsWeeklyTrend {
            get {
                return ResourceManager.GetString("strViolationsWeeklyTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count by Region Comparision with Weekly.
        /// </summary>
        public static string strViolationsWeekStatis {
            get {
                return ResourceManager.GetString("strViolationsWeekStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations Count by Region Comparision with Yearly .
        /// </summary>
        public static string strViolationsYearStatis {
            get {
                return ResourceManager.GetString("strViolationsYearStatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORK ZONES.
        /// </summary>
        public static string strWorkZones {
            get {
                return ResourceManager.GetString("strWorkZones", resourceCulture);
            }
        }
    }
}
