//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.WCF.SocialMediaService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("143360359367928")]
        public string FBAppId {
            get {
                return ((string)(this["FBAppId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FBAppSecret {
            get {
                return ((string)(this["FBAppSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CAANhtmK2gRABABrxSSOZA5OqPfoBtgJ2FeoINhebPbcF4WQGxTMkuI2qv3qpDDcWw5Ku82qMsXS2UMb9" +
            "3YPkXzVDbDEBsggZCNRHcWSvKN6VYJlSv6Ww4IMMgajZBYbTV5bUa4ZBh6Q7HA2DR7PuZCkWfgUeKlGK" +
            "OjggUrFqM5Bsj5HiC7d5JM3hpThq6lJQZD")]
        public string FBAccessToken {
            get {
                return ((string)(this["FBAccessToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pQWNNNf2FTKkVITzmRb181ccN")]
        public string TwitterConsumerId {
            get {
                return ((string)(this["TwitterConsumerId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LSgsxhvAn4oqGD4XJU2Y6HVicJv9EJAyFzV610Maxfv0okcUyj")]
        public string TwitterConsumerSecret {
            get {
                return ((string)(this["TwitterConsumerSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4641799162-CIE2qWwQoClU0RJl8bcRlU3GfmWlJyghIGl23aJ")]
        public string TwitterToken {
            get {
                return ((string)(this["TwitterToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JgqoEN0sz9OOAQvURvM1GKaghED3DxErChONvcZQG6HRD")]
        public string TwitterTokenSecret {
            get {
                return ((string)(this["TwitterTokenSecret"]));
            }
        }
    }
}
