//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatrolLastLocationDTO", Namespace="http://schemas.datacontract.org/2004/07/STC.Projects.ClassLibrary.DTO")]
    [System.SerializableAttribute()]
    public partial class PatrolLastLocationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AltitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ETATimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNoticedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRecommendedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LocationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfAssignedIncidentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatrolCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PatrolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PatrolImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PatrolLatLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PatrolOriginalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatrolPlateNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isPatrolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((this.AltitudeField.Equals(value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ETATime {
            get {
                return this.ETATimeField;
            }
            set {
                if ((this.ETATimeField.Equals(value) != true)) {
                    this.ETATimeField = value;
                    this.RaisePropertyChanged("ETATime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNoticed {
            get {
                return this.IsNoticedField;
            }
            set {
                if ((this.IsNoticedField.Equals(value) != true)) {
                    this.IsNoticedField = value;
                    this.RaisePropertyChanged("IsNoticed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRecommended {
            get {
                return this.IsRecommendedField;
            }
            set {
                if ((this.IsRecommendedField.Equals(value) != true)) {
                    this.IsRecommendedField = value;
                    this.RaisePropertyChanged("IsRecommended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LocationDate {
            get {
                return this.LocationDateField;
            }
            set {
                if ((this.LocationDateField.Equals(value) != true)) {
                    this.LocationDateField = value;
                    this.RaisePropertyChanged("LocationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfAssignedIncident {
            get {
                return this.NumberOfAssignedIncidentField;
            }
            set {
                if ((this.NumberOfAssignedIncidentField.Equals(value) != true)) {
                    this.NumberOfAssignedIncidentField = value;
                    this.RaisePropertyChanged("NumberOfAssignedIncident");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficerName {
            get {
                return this.OfficerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficerNameField, value) != true)) {
                    this.OfficerNameField = value;
                    this.RaisePropertyChanged("OfficerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatrolCode {
            get {
                return this.PatrolCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PatrolCodeField, value) != true)) {
                    this.PatrolCodeField = value;
                    this.RaisePropertyChanged("PatrolCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PatrolId {
            get {
                return this.PatrolIdField;
            }
            set {
                if ((this.PatrolIdField.Equals(value) != true)) {
                    this.PatrolIdField = value;
                    this.RaisePropertyChanged("PatrolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PatrolImage {
            get {
                return this.PatrolImageField;
            }
            set {
                if ((object.ReferenceEquals(this.PatrolImageField, value) != true)) {
                    this.PatrolImageField = value;
                    this.RaisePropertyChanged("PatrolImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PatrolLatLocationId {
            get {
                return this.PatrolLatLocationIdField;
            }
            set {
                if ((this.PatrolLatLocationIdField.Equals(value) != true)) {
                    this.PatrolLatLocationIdField = value;
                    this.RaisePropertyChanged("PatrolLatLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PatrolOriginalId {
            get {
                return this.PatrolOriginalIdField;
            }
            set {
                if ((this.PatrolOriginalIdField.Equals(value) != true)) {
                    this.PatrolOriginalIdField = value;
                    this.RaisePropertyChanged("PatrolOriginalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatrolPlateNo {
            get {
                return this.PatrolPlateNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PatrolPlateNoField, value) != true)) {
                    this.PatrolPlateNoField = value;
                    this.RaisePropertyChanged("PatrolPlateNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Speed {
            get {
                return this.SpeedField;
            }
            set {
                if ((this.SpeedField.Equals(value) != true)) {
                    this.SpeedField = value;
                    this.RaisePropertyChanged("Speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StatusId {
            get {
                return this.StatusIdField;
            }
            set {
                if ((this.StatusIdField.Equals(value) != true)) {
                    this.StatusIdField = value;
                    this.RaisePropertyChanged("StatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusName {
            get {
                return this.StatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNameField, value) != true)) {
                    this.StatusNameField = value;
                    this.RaisePropertyChanged("StatusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                if ((this.isDeletedField.Equals(value) != true)) {
                    this.isDeletedField = value;
                    this.RaisePropertyChanged("isDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isPatrol {
            get {
                return this.isPatrolField;
            }
            set {
                if ((this.isPatrolField.Equals(value) != true)) {
                    this.isPatrolField = value;
                    this.RaisePropertyChanged("isPatrol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatrolOfficersDetailsDTO", Namespace="http://schemas.datacontract.org/2004/07/STC.Projects.ClassLibrary.DTO")]
    [System.SerializableAttribute()]
    public partial class PatrolOfficersDetailsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.StaffPatrolModel[] OfficersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatrolAllocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatrolCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatrolPlateNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusArabicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusEnglishField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.StaffPatrolModel[] Officers {
            get {
                return this.OfficersField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficersField, value) != true)) {
                    this.OfficersField = value;
                    this.RaisePropertyChanged("Officers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatrolAllocation {
            get {
                return this.PatrolAllocationField;
            }
            set {
                if ((object.ReferenceEquals(this.PatrolAllocationField, value) != true)) {
                    this.PatrolAllocationField = value;
                    this.RaisePropertyChanged("PatrolAllocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatrolCode {
            get {
                return this.PatrolCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PatrolCodeField, value) != true)) {
                    this.PatrolCodeField = value;
                    this.RaisePropertyChanged("PatrolCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatrolPlateNumber {
            get {
                return this.PatrolPlateNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PatrolPlateNumberField, value) != true)) {
                    this.PatrolPlateNumberField = value;
                    this.RaisePropertyChanged("PatrolPlateNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusArabic {
            get {
                return this.StatusArabicField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusArabicField, value) != true)) {
                    this.StatusArabicField = value;
                    this.RaisePropertyChanged("StatusArabic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusEnglish {
            get {
                return this.StatusEnglishField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusEnglishField, value) != true)) {
                    this.StatusEnglishField = value;
                    this.RaisePropertyChanged("StatusEnglish");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StaffPatrolModel", Namespace="http://schemas.datacontract.org/2004/07/STC.Projects.ClassLibrary.DTO")]
    [System.SerializableAttribute()]
    public partial class StaffPatrolModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MilitaryNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MilitaryNumber {
            get {
                return this.MilitaryNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MilitaryNumberField, value) != true)) {
                    this.MilitaryNumberField = value;
                    this.RaisePropertyChanged("MilitaryNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TFMServiceReference.ITFMIntegrationService")]
    public interface ITFMIntegrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/AddDuty", ReplyAction="http://tempuri.org/ITFMIntegrationService/AddDutyResponse")]
        long AddDuty(System.Guid PatrolOrgId, string MessageContent, System.DateTime DutyDateTime, double Latitude, double Longitude, long NotificationId, int PatrolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/AddDuty", ReplyAction="http://tempuri.org/ITFMIntegrationService/AddDutyResponse")]
        System.Threading.Tasks.Task<long> AddDutyAsync(System.Guid PatrolOrgId, string MessageContent, System.DateTime DutyDateTime, double Latitude, double Longitude, long NotificationId, int PatrolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/AddIncident", ReplyAction="http://tempuri.org/ITFMIntegrationService/AddIncidentResponse")]
        bool AddIncident(System.Guid PatrolOrgId, System.DateTime IncidentDateTime, double Latitude, double Longitude, string MessageContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/AddIncident", ReplyAction="http://tempuri.org/ITFMIntegrationService/AddIncidentResponse")]
        System.Threading.Tasks.Task<bool> AddIncidentAsync(System.Guid PatrolOrgId, System.DateTime IncidentDateTime, double Latitude, double Longitude, string MessageContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/GetPatrolsLocations", ReplyAction="http://tempuri.org/ITFMIntegrationService/GetPatrolsLocationsResponse")]
        STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.PatrolLastLocationDTO[] GetPatrolsLocations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/GetPatrolsLocations", ReplyAction="http://tempuri.org/ITFMIntegrationService/GetPatrolsLocationsResponse")]
        System.Threading.Tasks.Task<STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.PatrolLastLocationDTO[]> GetPatrolsLocationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/UpdatePatrolLocations", ReplyAction="http://tempuri.org/ITFMIntegrationService/UpdatePatrolLocationsResponse")]
        bool UpdatePatrolLocations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/UpdatePatrolLocations", ReplyAction="http://tempuri.org/ITFMIntegrationService/UpdatePatrolLocationsResponse")]
        System.Threading.Tasks.Task<bool> UpdatePatrolLocationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/GetPatrolDetails", ReplyAction="http://tempuri.org/ITFMIntegrationService/GetPatrolDetailsResponse")]
        STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.PatrolLastLocationDTO GetPatrolDetails(int PatrolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/GetPatrolDetails", ReplyAction="http://tempuri.org/ITFMIntegrationService/GetPatrolDetailsResponse")]
        System.Threading.Tasks.Task<STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.PatrolLastLocationDTO> GetPatrolDetailsAsync(int PatrolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/UpdatePatrolCurrentTask", ReplyAction="http://tempuri.org/ITFMIntegrationService/UpdatePatrolCurrentTaskResponse")]
        bool UpdatePatrolCurrentTask(System.Guid patrolOriginalId, long taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/UpdatePatrolCurrentTask", ReplyAction="http://tempuri.org/ITFMIntegrationService/UpdatePatrolCurrentTaskResponse")]
        System.Threading.Tasks.Task<bool> UpdatePatrolCurrentTaskAsync(System.Guid patrolOriginalId, long taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/GetTaskImagesURLs", ReplyAction="http://tempuri.org/ITFMIntegrationService/GetTaskImagesURLsResponse")]
        string[] GetTaskImagesURLs(long taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/GetTaskImagesURLs", ReplyAction="http://tempuri.org/ITFMIntegrationService/GetTaskImagesURLsResponse")]
        System.Threading.Tasks.Task<string[]> GetTaskImagesURLsAsync(long taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/GetTaskVideosURLs", ReplyAction="http://tempuri.org/ITFMIntegrationService/GetTaskVideosURLsResponse")]
        string[] GetTaskVideosURLs(long taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/GetTaskVideosURLs", ReplyAction="http://tempuri.org/ITFMIntegrationService/GetTaskVideosURLsResponse")]
        System.Threading.Tasks.Task<string[]> GetTaskVideosURLsAsync(long taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/GetPatrolDetailsFromTFM", ReplyAction="http://tempuri.org/ITFMIntegrationService/GetPatrolDetailsFromTFMResponse")]
        STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.PatrolOfficersDetailsDTO GetPatrolDetailsFromTFM(System.Guid patrolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMIntegrationService/GetPatrolDetailsFromTFM", ReplyAction="http://tempuri.org/ITFMIntegrationService/GetPatrolDetailsFromTFMResponse")]
        System.Threading.Tasks.Task<STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.PatrolOfficersDetailsDTO> GetPatrolDetailsFromTFMAsync(System.Guid patrolId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITFMIntegrationServiceChannel : STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.ITFMIntegrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TFMIntegrationServiceClient : System.ServiceModel.ClientBase<STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.ITFMIntegrationService>, STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.ITFMIntegrationService {
        
        public TFMIntegrationServiceClient() {
        }
        
        public TFMIntegrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TFMIntegrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFMIntegrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFMIntegrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long AddDuty(System.Guid PatrolOrgId, string MessageContent, System.DateTime DutyDateTime, double Latitude, double Longitude, long NotificationId, int PatrolId) {
            return base.Channel.AddDuty(PatrolOrgId, MessageContent, DutyDateTime, Latitude, Longitude, NotificationId, PatrolId);
        }
        
        public System.Threading.Tasks.Task<long> AddDutyAsync(System.Guid PatrolOrgId, string MessageContent, System.DateTime DutyDateTime, double Latitude, double Longitude, long NotificationId, int PatrolId) {
            return base.Channel.AddDutyAsync(PatrolOrgId, MessageContent, DutyDateTime, Latitude, Longitude, NotificationId, PatrolId);
        }
        
        public bool AddIncident(System.Guid PatrolOrgId, System.DateTime IncidentDateTime, double Latitude, double Longitude, string MessageContent) {
            return base.Channel.AddIncident(PatrolOrgId, IncidentDateTime, Latitude, Longitude, MessageContent);
        }
        
        public System.Threading.Tasks.Task<bool> AddIncidentAsync(System.Guid PatrolOrgId, System.DateTime IncidentDateTime, double Latitude, double Longitude, string MessageContent) {
            return base.Channel.AddIncidentAsync(PatrolOrgId, IncidentDateTime, Latitude, Longitude, MessageContent);
        }
        
        public STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.PatrolLastLocationDTO[] GetPatrolsLocations() {
            return base.Channel.GetPatrolsLocations();
        }
        
        public System.Threading.Tasks.Task<STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.PatrolLastLocationDTO[]> GetPatrolsLocationsAsync() {
            return base.Channel.GetPatrolsLocationsAsync();
        }
        
        public bool UpdatePatrolLocations() {
            return base.Channel.UpdatePatrolLocations();
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePatrolLocationsAsync() {
            return base.Channel.UpdatePatrolLocationsAsync();
        }
        
        public STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.PatrolLastLocationDTO GetPatrolDetails(int PatrolId) {
            return base.Channel.GetPatrolDetails(PatrolId);
        }
        
        public System.Threading.Tasks.Task<STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.PatrolLastLocationDTO> GetPatrolDetailsAsync(int PatrolId) {
            return base.Channel.GetPatrolDetailsAsync(PatrolId);
        }
        
        public bool UpdatePatrolCurrentTask(System.Guid patrolOriginalId, long taskId) {
            return base.Channel.UpdatePatrolCurrentTask(patrolOriginalId, taskId);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePatrolCurrentTaskAsync(System.Guid patrolOriginalId, long taskId) {
            return base.Channel.UpdatePatrolCurrentTaskAsync(patrolOriginalId, taskId);
        }
        
        public string[] GetTaskImagesURLs(long taskId) {
            return base.Channel.GetTaskImagesURLs(taskId);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTaskImagesURLsAsync(long taskId) {
            return base.Channel.GetTaskImagesURLsAsync(taskId);
        }
        
        public string[] GetTaskVideosURLs(long taskId) {
            return base.Channel.GetTaskVideosURLs(taskId);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTaskVideosURLsAsync(long taskId) {
            return base.Channel.GetTaskVideosURLsAsync(taskId);
        }
        
        public STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.PatrolOfficersDetailsDTO GetPatrolDetailsFromTFM(System.Guid patrolId) {
            return base.Channel.GetPatrolDetailsFromTFM(patrolId);
        }
        
        public System.Threading.Tasks.Task<STC.Projects.WPFControlLibrary.MapControl.TFMServiceReference.PatrolOfficersDetailsDTO> GetPatrolDetailsFromTFMAsync(System.Guid patrolId) {
            return base.Channel.GetPatrolDetailsFromTFMAsync(patrolId);
        }
    }
}
