//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.WCF.ServiceLayer.STCTFMService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="STCTFMService.ITFMService")]
    public interface ITFMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMService/GetTaskImagesURLs", ReplyAction="http://tempuri.org/ITFMService/GetTaskImagesURLsResponse")]
        string[] GetTaskImagesURLs(long taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMService/GetTaskImagesURLs", ReplyAction="http://tempuri.org/ITFMService/GetTaskImagesURLsResponse")]
        System.Threading.Tasks.Task<string[]> GetTaskImagesURLsAsync(long taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMService/GetTaskVideosURLs", ReplyAction="http://tempuri.org/ITFMService/GetTaskVideosURLsResponse")]
        string[] GetTaskVideosURLs(long taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMService/GetTaskVideosURLs", ReplyAction="http://tempuri.org/ITFMService/GetTaskVideosURLsResponse")]
        System.Threading.Tasks.Task<string[]> GetTaskVideosURLsAsync(long taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMService/GetPatrolDetails", ReplyAction="http://tempuri.org/ITFMService/GetPatrolDetailsResponse")]
        STC.Projects.ClassLibrary.DTO.PatrolOfficersDetailsDTO GetPatrolDetails(System.Guid patrolId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITFMService/GetPatrolDetails", ReplyAction="http://tempuri.org/ITFMService/GetPatrolDetailsResponse")]
        System.Threading.Tasks.Task<STC.Projects.ClassLibrary.DTO.PatrolOfficersDetailsDTO> GetPatrolDetailsAsync(System.Guid patrolId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITFMServiceChannel : STC.Projects.WCF.ServiceLayer.STCTFMService.ITFMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TFMServiceClient : System.ServiceModel.ClientBase<STC.Projects.WCF.ServiceLayer.STCTFMService.ITFMService>, STC.Projects.WCF.ServiceLayer.STCTFMService.ITFMService {
        
        public TFMServiceClient() {
        }
        
        public TFMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TFMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetTaskImagesURLs(long taskId) {
            return base.Channel.GetTaskImagesURLs(taskId);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTaskImagesURLsAsync(long taskId) {
            return base.Channel.GetTaskImagesURLsAsync(taskId);
        }
        
        public string[] GetTaskVideosURLs(long taskId) {
            return base.Channel.GetTaskVideosURLs(taskId);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTaskVideosURLsAsync(long taskId) {
            return base.Channel.GetTaskVideosURLsAsync(taskId);
        }
        
        public STC.Projects.ClassLibrary.DTO.PatrolOfficersDetailsDTO GetPatrolDetails(System.Guid patrolId) {
            return base.Channel.GetPatrolDetails(patrolId);
        }
        
        public System.Threading.Tasks.Task<STC.Projects.ClassLibrary.DTO.PatrolOfficersDetailsDTO> GetPatrolDetailsAsync(System.Guid patrolId) {
            return base.Channel.GetPatrolDetailsAsync(patrolId);
        }
    }
}
