//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityItem
    {
        public long ActivityItemId { get; set; }
        public Nullable<System.Guid> ActivityItemGuid { get; set; }
        public string ActivityItemDescription { get; set; }
        public long ActivityId { get; set; }
        public Nullable<System.Guid> ActivityGuid { get; set; }
        public long ItemId { get; set; }
        public Nullable<System.Guid> ItemGuid { get; set; }
        public Nullable<long> SourceId { get; set; }
        public int ItemInvolvementId { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> RowStatusId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Item Item { get; set; }
        public virtual ItemInvolvementDIM ItemInvolvementDIM { get; set; }
    }
}
