//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.DangerousVehicleViolations = new HashSet<DangerousVehicleViolation>();
            this.DangerousVehicleViolations1 = new HashSet<DangerousVehicleViolation>();
            this.ActivityPersons = new HashSet<ActivityPersonView>();
            this.ActivityItems = new HashSet<ActivityItem>();
            this.ActivityLocations = new HashSet<ActivityLocation>();
        }
    
        public long ActivityId { get; set; }
        public Nullable<System.Guid> ActivityGuid { get; set; }
        public string OriginalIdent { get; set; }
        public long SourceId { get; set; }
        public int ActivityCategoryId { get; set; }
        public int ActivityReasonId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> ImportanceHighLowId { get; set; }
        public Nullable<int> HighLowId { get; set; }
        public string ActivityName { get; set; }
        public string ActivityDescription { get; set; }
        public Nullable<System.DateTime> ActivityStartDate { get; set; }
        public Nullable<System.DateTime> ActivityEndDate { get; set; }
        public Nullable<System.DateTime> ActivityDueDate { get; set; }
        public Nullable<System.DateTime> ActivityExpirationDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> RowStatusId { get; set; }
    
        public virtual ICollection<DangerousVehicleViolation> DangerousVehicleViolations { get; set; }
        public virtual ICollection<DangerousVehicleViolation> DangerousVehicleViolations1 { get; set; }
        public virtual ICollection<ActivityPersonView> ActivityPersons { get; set; }
        public virtual Source Source { get; set; }
        public virtual ActivityCategoryDIM ActivityCategoryDIM { get; set; }
        public virtual ICollection<ActivityItem> ActivityItems { get; set; }
        public virtual ICollection<ActivityLocation> ActivityLocations { get; set; }
        public virtual ActivityReasonDIM ActivityReasonDIM { get; set; }
        public virtual StatusDIM StatusDIM { get; set; }
    }
}
