//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityPersonView
    {
        public long ActivityPersonId { get; set; }
        public string ActivityPersonDescription { get; set; }
        public long PersonId { get; set; }
        public long ActivityId { get; set; }
        public string SourceName { get; set; }
        public string PersonInvolvementCode { get; set; }
        public string PersonInvolvementDescription { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public string RowStatusCode { get; set; }
        public string RowStatusDescription { get; set; }
    
        public virtual ServiceCall ServiceCall { get; set; }
        public virtual PersonView Person { get; set; }
        public virtual ServiceCallDriver ServiceCallDriver { get; set; }
        public virtual Activity Activity { get; set; }
    }
}
