//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityPerson
    {
        public long ActivityPersonId { get; set; }
        public Nullable<System.Guid> ActivityPersonGuid { get; set; }
        public string ActivityPersonDescription { get; set; }
        public long PersonId { get; set; }
        public Nullable<System.Guid> PersonGuid { get; set; }
        public long ActivityId { get; set; }
        public Nullable<System.Guid> ActivityGuid { get; set; }
        public long SourceId { get; set; }
        public int PersonInvolvementId { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> RowStatusId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Source Source { get; set; }
        public virtual Person Person { get; set; }
        public virtual PersonInvolvementDIM PersonInvolvementDIM { get; set; }
    }
}
