//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetLastStatusView
    {
        public int AssetLastStatusId { get; set; }
        public string AssetId { get; set; }
        public string AssetCode { get; set; }
        public int AssetStatusId { get; set; }
        public string AssetStatusName { get; set; }
        public System.DateTime DateChanged { get; set; }
        public bool IsNoticed { get; set; }
        public Nullable<int> AssetTypeId { get; set; }
        public string AssetTypeName { get; set; }
    }
}
