//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomaticReportsLog
    {
        public long LogId { get; set; }
        public int ReportGroupId { get; set; }
        public int UserId { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public string SMSText { get; set; }
        public string EmailText { get; set; }
        public System.DateTime SendDate { get; set; }
        public string EmailSubject { get; set; }
        public string EnglishSMSText { get; set; }
        public string EnglishEmailText { get; set; }
    
        public virtual AutomaticReportGroups AutomaticReportGroups { get; set; }
        public virtual User Users { get; set; }
    }
}
