//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomaticReportGroups
    {
        public AutomaticReportGroups()
        {
            this.AutomaticReportsLog = new HashSet<AutomaticReportsLog>();
        }
    
        public int ReportGroupId { get; set; }
        public int ReportId { get; set; }
        public int GroupId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AutomaticReports AutomaticReports { get; set; }
        public virtual ICollection<AutomaticReportsLog> AutomaticReportsLog { get; set; }
        public virtual Group Group { get; set; }
    }
}
