//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomaticReportDiminsion
    {
        public int ReportDiminsionId { get; set; }
        public int ReportId { get; set; }
        public int DiminsionId { get; set; }
        public bool IsStaticValue { get; set; }
        public string ExactValue { get; set; }
        public Nullable<double> RelativeValue { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> RelativeTypeId { get; set; }
    
        public virtual AutomaticReports AutomaticReports { get; set; }
        public virtual ParameterDiminsions ParameterDiminsions { get; set; }
        public virtual DiminsionRelativeTypeId DiminsionRelativeTypeId { get; set; }
    }
}
