//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessRulePriority
    {
        public BusinessRulePriority()
        {
            this.CorrelationBusinessRules = new HashSet<CorrelationBusinessRule>();
            this.UsersUserControls = new HashSet<UsersUserControl>();
            this.Conf_SOPSourceSOP = new HashSet<Conf_SOPSourceSOP>();
        }
    
        public int BusinessRulePriorityId { get; set; }
        public string PriorityNameAr { get; set; }
        public string PriorityNameEn { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<CorrelationBusinessRule> CorrelationBusinessRules { get; set; }
        public virtual ICollection<UsersUserControl> UsersUserControls { get; set; }
        public virtual ICollection<Conf_SOPSourceSOP> Conf_SOPSourceSOP { get; set; }
    }
}
