//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckedInPatrolView
    {
        public int CheckedInPatrolId { get; set; }
        public int PatrolId { get; set; }
        public string PatrolCode { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public string PlateNumber { get; set; }
    }
}
