//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conf_ControlPageMessages
    {
        public long ControlPageMessageId { get; set; }
        public long PageDetailsId { get; set; }
        public int UserControlMessageId { get; set; }
    
        public virtual Conf_PageDetails Conf_PageDetails { get; set; }
        public virtual Conf_UserControlMessage Conf_UserControlMessage { get; set; }
    }
}
