//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conf_ControlPagePublisherMessages
    {
        public long ControlPagePublisherMessageId { get; set; }
        public long PageDetailsId { get; set; }
        public int UserControlPublisherMessageId { get; set; }
        public string PublisherExpression { get; set; }
    
        public virtual Conf_PageDetails Conf_PageDetails { get; set; }
        public virtual Conf_UserControlPublisherMessage Conf_UserControlPublisherMessage { get; set; }
    }
}
