//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conf_SOPSourceSOP
    {
        public long Id { get; set; }
        public int SOPId { get; set; }
        public int SourceId { get; set; }
        public int Rank { get; set; }
        public string SOPViewModelType { get; set; }
        public string SOPViewDetailsControl { get; set; }
        public Nullable<int> SOPViewDetailsMessageId { get; set; }
        public Nullable<int> SOPViewListMessageId { get; set; }
        public Nullable<int> PriorityId { get; set; }
    
        public virtual BusinessRulePriority BusinessRulePriority { get; set; }
        public virtual Conf_SOP Conf_SOP { get; set; }
        public virtual Conf_SOPSource Conf_SOPSource { get; set; }
    }
}
