//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conf_SOP
    {
        public Conf_SOP()
        {
            this.Conf_SOPSourceSOP = new HashSet<Conf_SOPSourceSOP>();
            this.NotificationSOPLogs = new HashSet<NotificationSOPLog>();
        }
    
        public int SOPId { get; set; }
        public string SOPContent { get; set; }
        public string SOPViewModelType { get; set; }
        public string SOPViewDetailsControl { get; set; }
        public Nullable<int> SOPViewDetailsMessageId { get; set; }
        public Nullable<int> SOPViewListMessageId { get; set; }
        public Nullable<bool> IsConfigure { get; set; }
    
        public virtual ICollection<Conf_SOPSourceSOP> Conf_SOPSourceSOP { get; set; }
        public virtual ICollection<NotificationSOPLog> NotificationSOPLogs { get; set; }
    }
}
