//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conf_Layout
    {
        public Conf_Layout()
        {
            this.Conf_LayoutsPlaceHolders = new HashSet<Conf_LayoutsPlaceHolders>();
        }
    
        public int LayoutId { get; set; }
        public string LayoutName { get; set; }
        public string Xaml { get; set; }
    
        public virtual ICollection<Conf_LayoutsPlaceHolders> Conf_LayoutsPlaceHolders { get; set; }
    }
}
