//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conf_Pages
    {
        public Conf_Pages()
        {
            this.Conf_PageDetails = new HashSet<Conf_PageDetails>();
            this.Conf_UsersPages = new HashSet<Conf_UsersPages>();
            this.Features = new HashSet<Feature>();
        }
    
        public long PageId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Conf_PageDetails> Conf_PageDetails { get; set; }
        public virtual ICollection<Conf_UsersPages> Conf_UsersPages { get; set; }
        public virtual ICollection<Feature> Features { get; set; }
    }
}
