//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationView
    {
        public int UserId { get; set; }
        public long PageId { get; set; }
        public string Name { get; set; }
        public long LayoutPlaceHolderId { get; set; }
        public int UserControlId { get; set; }
        public long PageDetailsId { get; set; }
        public int PlaceHolderID { get; set; }
        public int LayoutId { get; set; }
        public string LayoutName { get; set; }
        public string Xaml { get; set; }
        public string PlaceHolderName { get; set; }
        public string UserControlName { get; set; }
        public string PublisherExpression { get; set; }
        public int MessageTypeId { get; set; }
        public int PublisherMessageTypeId { get; set; }
        public string SubscriberMessage { get; set; }
        public string PublisherMessage { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> FeatureId { get; set; }
    }
}
