//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conf_SOPSource
    {
        public Conf_SOPSource()
        {
            this.Conf_SOPSourceSOP = new HashSet<Conf_SOPSourceSOP>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsConfigure { get; set; }
        public string ArabicDescription { get; set; }
        public string EnglishDescription { get; set; }
    
        public virtual ICollection<Conf_SOPSourceSOP> Conf_SOPSourceSOP { get; set; }
    }
}
