//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conf_PageDetails
    {
        public Conf_PageDetails()
        {
            this.Conf_ControlPageMessages = new HashSet<Conf_ControlPageMessages>();
            this.Conf_ControlPagePublisherMessages = new HashSet<Conf_ControlPagePublisherMessages>();
        }
    
        public long PageDetailsId { get; set; }
        public long PageId { get; set; }
        public long LayoutPlaceHolderId { get; set; }
        public int UserControlId { get; set; }
    
        public virtual ICollection<Conf_ControlPageMessages> Conf_ControlPageMessages { get; set; }
        public virtual Conf_LayoutsPlaceHolders Conf_LayoutsPlaceHolders { get; set; }
        public virtual Conf_Pages Conf_Pages { get; set; }
        public virtual Conf_UserControl Conf_UserControl { get; set; }
        public virtual ICollection<Conf_ControlPagePublisherMessages> Conf_ControlPagePublisherMessages { get; set; }
    }
}
