//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conf_UserControl
    {
        public Conf_UserControl()
        {
            this.Conf_PageDetails = new HashSet<Conf_PageDetails>();
            this.Conf_UserControlMessage = new HashSet<Conf_UserControlMessage>();
            this.Conf_UserControlPublisherMessage = new HashSet<Conf_UserControlPublisherMessage>();
        }
    
        public int UserControlId { get; set; }
        public string UserControlName { get; set; }
    
        public virtual ICollection<Conf_PageDetails> Conf_PageDetails { get; set; }
        public virtual ICollection<Conf_UserControlMessage> Conf_UserControlMessage { get; set; }
        public virtual ICollection<Conf_UserControlPublisherMessage> Conf_UserControlPublisherMessage { get; set; }
    }
}
