//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelationViolationDetail
    {
        public long CorrelationViolationDetailsId { get; set; }
        public int ViolationTypeId { get; set; }
        public Nullable<int> OverSpeedDetailsId { get; set; }
        public Nullable<int> TrraficCrossTimeDetailsId { get; set; }
        public long CorrelationRuleId { get; set; }
        public bool IsDeleted { get; set; }
        public int ViolationQty { get; set; }
    
        public virtual OverSpeed OverSpeed { get; set; }
        public virtual TrafficCrossTime TrafficCrossTime { get; set; }
        public virtual NewCorrelationRule NewCorrelationRule { get; set; }
    }
}
