//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelationMessagesLogView
    {
        public int BusinessRuleId { get; set; }
        public string PlateNumber { get; set; }
        public string PlateColor { get; set; }
        public string PlateKind { get; set; }
        public string PlateSource { get; set; }
        public string RuleName { get; set; }
        public Nullable<System.DateTime> CorrelationDate { get; set; }
        public long LogId { get; set; }
    }
}
