//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelationDriverDetail
    {
        public CorrelationDriverDetail()
        {
            this.NewCorrelationRules = new HashSet<NewCorrelationRule>();
        }
    
        public int CorrelationDriverDetailsId { get; set; }
        public int AgeFrom { get; set; }
        public int AgeTo { get; set; }
    
        public virtual ICollection<NewCorrelationRule> NewCorrelationRules { get; set; }
    }
}
