//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class elroc
    {
        public int no { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> server_no { get; set; }
        public Nullable<int> camera_no { get; set; }
        public string license_plate { get; set; }
        public string color_code { get; set; }
        public Nullable<int> plate_kind { get; set; }
        public Nullable<int> plate_type { get; set; }
        public Nullable<int> plate_source { get; set; }
        public Nullable<int> plate_color { get; set; }
        public Nullable<int> speed { get; set; }
        public Nullable<int> speed_limit { get; set; }
        public Nullable<int> captured_speed { get; set; }
        public Nullable<int> alarm_info { get; set; }
        public Nullable<int> alarm_status { get; set; }
        public Nullable<int> size_class { get; set; }
        public string latitude { get; set; }
        public string longtitude { get; set; }
        public string altitude { get; set; }
        public Nullable<int> direction { get; set; }
        public Nullable<int> lane_no { get; set; }
        public string pic_filename { get; set; }
        public Nullable<int> location_code { get; set; }
        public Nullable<int> old_elroc_no { get; set; }
        public Nullable<bool> send_state { get; set; }
        public string gps_data { get; set; }
        public Nullable<bool> webservice_state { get; set; }
        public Nullable<int> plate_code { get; set; }
    
        public virtual server server { get; set; }
    }
}
