//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyContact
    {
        public EmergencyContact()
        {
            this.ContactItems = new HashSet<ContactItem>();
        }
    
        public int EmergencyContactId { get; set; }
        public string AuthorityName { get; set; }
    
        public virtual ICollection<ContactItem> ContactItems { get; set; }
    }
}
