//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public Feature()
        {
            this.RoleFeatures = new HashSet<RoleFeature>();
        }
    
        public int FeatureId { get; set; }
        public Nullable<long> PageId { get; set; }
        public string FeatureNameAr { get; set; }
        public string FeatureNameEn { get; set; }
    
        public virtual Conf_Pages Conf_Pages { get; set; }
        public virtual ICollection<RoleFeature> RoleFeatures { get; set; }
    }
}
