//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentView
    {
        public long IncidentId { get; set; }
        public string IncidentNumber { get; set; }
        public int IncidentTypeId { get; set; }
        public string IncidentTypeName { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public string IncidentAddress { get; set; }
        public string CallerName { get; set; }
        public string CallerNumber { get; set; }
        public string CallerAddress { get; set; }
        public string CallerLanguage { get; set; }
        public Nullable<int> CallTakerId { get; set; }
        public string CallTakerName { get; set; }
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> DispatcherId { get; set; }
        public string DispatcherName { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> DispatcheTime { get; set; }
        public Nullable<System.DateTime> ArrivedTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool IsNoticed { get; set; }
        public Nullable<bool> IsCritical { get; set; }
        public Nullable<long> NotificationId { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> CauseId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> CrashSeverityId { get; set; }
        public Nullable<int> CrashTypeId { get; set; }
        public Nullable<int> EmirateId { get; set; }
        public Nullable<int> IntersectionId { get; set; }
        public Nullable<int> LightingId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> LocationTypeId { get; set; }
        public Nullable<int> PConditionId { get; set; }
        public Nullable<int> RoadTypeId { get; set; }
        public Nullable<int> WeatherId { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> LanesCount { get; set; }
        public Nullable<int> SlightInjuries { get; set; }
        public Nullable<int> MediumInjuries { get; set; }
        public Nullable<int> SevereInjuries { get; set; }
        public Nullable<int> Fatalities { get; set; }
        public Nullable<int> TotalInjuriesFatalities { get; set; }
        public string IncidentDescription { get; set; }
        public string LocationDescription { get; set; }
        public string ZoneDescription { get; set; }
        public string PoliceStation { get; set; }
        public string CauseName { get; set; }
        public string CityName { get; set; }
        public string CrashSeverityName { get; set; }
        public string CrashTypeName { get; set; }
        public string IntersectionName { get; set; }
        public string EmirateName { get; set; }
        public string LocationName { get; set; }
        public string LightingName { get; set; }
        public string RoadTypeName { get; set; }
        public string LocationTypeName { get; set; }
        public string WeatherName { get; set; }
        public string PConditionName { get; set; }
        public Nullable<int> PoliceStationId { get; set; }
    }
}
