//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public long IncidentId { get; set; }
        public string IncidentNumber { get; set; }
        public Nullable<int> IncidentTypeId { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public string IncidentAddress { get; set; }
        public string CallerName { get; set; }
        public string CallerNumber { get; set; }
        public string CallerAddress { get; set; }
        public string CallerLanguage { get; set; }
        public Nullable<int> CallTakerId { get; set; }
        public string CallTakerName { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> DispatcherId { get; set; }
        public string DispatcherName { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> DispatcheTime { get; set; }
        public Nullable<System.DateTime> ArrivedTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> IsNoticed { get; set; }
        public Nullable<bool> IsCritical { get; set; }
        public Nullable<long> NotificationId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> CauseId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> CrashSeverityId { get; set; }
        public Nullable<int> CrashTypeId { get; set; }
        public Nullable<int> EmirateId { get; set; }
        public Nullable<int> IntersectionId { get; set; }
        public Nullable<int> LightingId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> LocationTypeId { get; set; }
        public Nullable<int> PConditionId { get; set; }
        public Nullable<int> RoadTypeId { get; set; }
        public Nullable<int> WeatherId { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> LanesCount { get; set; }
        public Nullable<int> SlightInjuries { get; set; }
        public Nullable<int> MediumInjuries { get; set; }
        public Nullable<int> SevereInjuries { get; set; }
        public Nullable<int> Fatalities { get; set; }
        public Nullable<int> TotalInjuriesFatalities { get; set; }
        public string IncidentDescription { get; set; }
        public string LocationDescription { get; set; }
        public string ZoneDescription { get; set; }
        public Nullable<int> PoliceStationId { get; set; }
        public Nullable<int> OriginalFileId { get; set; }
    
        public virtual IncidentArea IncidentArea { get; set; }
        public virtual IncidentCause IncidentCause { get; set; }
        public virtual IncidentCity IncidentCity { get; set; }
        public virtual IncidentCrashSeverity IncidentCrashSeverity { get; set; }
        public virtual IncidentCrashType IncidentCrashType { get; set; }
        public virtual IncidentEmirate IncidentEmirate { get; set; }
        public virtual IncidentIntersection IncidentIntersection { get; set; }
        public virtual IncidentLighting IncidentLighting { get; set; }
        public virtual IncidentLocation IncidentLocation { get; set; }
        public virtual IncidentLocationType IncidentLocationType { get; set; }
        public virtual IncidentPCondition IncidentPCondition { get; set; }
        public virtual IncidentPoliceStation IncidentPoliceStation { get; set; }
        public virtual IncidentRoadType IncidentRoadType { get; set; }
        public virtual IncidentStatus IncidentStatus { get; set; }
        public virtual IncidentType IncidentType { get; set; }
        public virtual IncidentWeather IncidentWeather { get; set; }
        public virtual Notification Notifications { get; set; }
    }
}
