//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemRegistrations = new HashSet<ItemRegistration>();
            this.ActivityItems = new HashSet<ActivityItem>();
        }
    
        public long ItemId { get; set; }
        public Nullable<System.Guid> ItemGuid { get; set; }
        public string OriginalIdent { get; set; }
        public long SourceId { get; set; }
        public Nullable<int> ItemCategoryId { get; set; }
        public Nullable<int> ItemStatusId { get; set; }
        public Nullable<int> ItemMakeModelId { get; set; }
        public Nullable<int> ModelYear { get; set; }
        public Nullable<int> ItemPrimaryColorId { get; set; }
        public Nullable<int> ItemSecondaryColorId { get; set; }
        public Nullable<int> ItemConditionId { get; set; }
        public Nullable<int> ItemUsageId { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public string SerialIdentification { get; set; }
        public Nullable<double> ItemValue { get; set; }
        public string SizeDescription { get; set; }
        public Nullable<double> HeightMeasure { get; set; }
        public Nullable<double> LengthMeasure { get; set; }
        public Nullable<double> WidthMeasure { get; set; }
        public Nullable<double> WeightMeasure { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> RowStatusId { get; set; }
    
        public virtual Source Source { get; set; }
        public virtual ICollection<ItemRegistration> ItemRegistrations { get; set; }
        public virtual ItemCategoryDIM ItemCategoryDIM { get; set; }
        public virtual ICollection<ActivityItem> ActivityItems { get; set; }
    }
}
