//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemView
    {
        public ItemView()
        {
            this.ActivityItems = new HashSet<ActivityItemView>();
        }
    
        public long ItemId { get; set; }
        public string OriginalIdent { get; set; }
        public string SourceName { get; set; }
        public string ItemCategoryCode { get; set; }
        public string ItemCategoryDescription { get; set; }
        public string ItemStatusCode { get; set; }
        public string ItemStatusDescription { get; set; }
        public string ItemMakeModelCode { get; set; }
        public string ItemMakeModelMake { get; set; }
        public string ItemMakeModelModel { get; set; }
        public Nullable<int> ModelYear { get; set; }
        public string ItemPrimaryColorCode { get; set; }
        public string ItemPrimaryColorDescription { get; set; }
        public string ItemSecondaryColorCode { get; set; }
        public string ItemSecondaryColorDescription { get; set; }
        public string ItemConditionCode { get; set; }
        public string ItemConditionDescription { get; set; }
        public string ItemUsageCode { get; set; }
        public string ItemUsageDescription { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public string SerialIdentification { get; set; }
        public Nullable<double> ItemValue { get; set; }
        public string SizeDescription { get; set; }
        public Nullable<double> HeightMeasure { get; set; }
        public Nullable<double> LengthMeasure { get; set; }
        public Nullable<double> WidthMeasure { get; set; }
        public Nullable<double> WeightMeasure { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public string RowStatusCode { get; set; }
        public string RowStatusDescription { get; set; }
    
        public virtual ICollection<ActivityItemView> ActivityItems { get; set; }
    }
}
