//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationView
    {
        public LocationView()
        {
            this.ActivityLocations = new HashSet<ActivityLocationView>();
        }
    
        public long LocationId { get; set; }
        public string OriginalIdent { get; set; }
        public string SourceName { get; set; }
        public string LocationCategoryCode { get; set; }
        public string LocationCategoryDescription { get; set; }
        public string locationDatumCode { get; set; }
        public string locationDatumDescription { get; set; }
        public string locationIntersectionTypeCode { get; set; }
        public string locationIntersectionTypeDescription { get; set; }
        public string LocationName { get; set; }
        public string Description { get; set; }
        public string GeoLEOCode { get; set; }
        public string GeoLEODivision { get; set; }
        public string GeoLEODistrict { get; set; }
        public string GeoLEOSector { get; set; }
        public string GeoLEOBeat { get; set; }
        public string GeoLEODescription { get; set; }
        public string GeoLocationSubDivisionState { get; set; }
        public string GeoLocationSubDivisionCounty { get; set; }
        public string GeoLocationSubDivisionCity { get; set; }
        public string GeoLocationSubDivisionSubDivision { get; set; }
        public string GeoCountryCode { get; set; }
        public string GeoCountryCountryName { get; set; }
        public string GeoCityCode { get; set; }
        public string GeoCityCityName { get; set; }
        public string GeoCityStateName { get; set; }
        public string GeoCityCountyName { get; set; }
        public string GeoCountyCode { get; set; }
        public string GeoCountyCountyName { get; set; }
        public string GeoCountyStateName { get; set; }
        public string GeoZipCode { get; set; }
        public string GeoZipZipCode { get; set; }
        public string GeoStateCode { get; set; }
        public string GeoStateStateName { get; set; }
        public string GeoCensusTractCode { get; set; }
        public string GeoCensusTractDescription { get; set; }
        public string LocationStreetCategoryCode { get; set; }
        public string LocationStreetCategoryDescription { get; set; }
        public string LocationStreetDirectionPrefixCode { get; set; }
        public string LocationStreetDirectionPrefixDescription { get; set; }
        public string LocationStreetDirectionSuffixCode { get; set; }
        public string LocationStreetDirectionSuffixDescription { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string StreetExtension { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PostalCode { get; set; }
        public string PostalCodeExtension { get; set; }
        public string CrossStreet { get; set; }
        public string HighwayPosition { get; set; }
        public System.Data.Entity.Spatial.DbGeometry GeoPoint { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Boundry { get; set; }
        public string Unit { get; set; }
        public string Floor { get; set; }
        public string PostOfficeBox { get; set; }
        public Nullable<double> AltitudeAGL { get; set; }
        public Nullable<double> AltitudeMSL { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string OrgAddress1 { get; set; }
        public string OrgAddress2 { get; set; }
        public string OrgAddress3 { get; set; }
        public string OrgStateCode { get; set; }
        public string OrgCountry { get; set; }
        public string OrgConty { get; set; }
        public string OrgCity { get; set; }
        public string OrgZip { get; set; }
        public string OrgLat { get; set; }
        public string OrgLong { get; set; }
        public Nullable<bool> OrgLeoProcessed { get; set; }
        public Nullable<bool> OrgSubProcessed { get; set; }
        public Nullable<bool> OrgLocProcessed { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public string RowStatusCode { get; set; }
        public string RowStatusDescription { get; set; }
    
        public virtual ICollection<ActivityLocationView> ActivityLocations { get; set; }
    }
}
