//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.ActivityLocations = new HashSet<ActivityLocation>();
        }
    
        public long LocationId { get; set; }
        public Nullable<System.Guid> LocationGuid { get; set; }
        public string OriginalIdent { get; set; }
        public long SourceId { get; set; }
        public int LocationCategoryId { get; set; }
        public int locationDatumId { get; set; }
        public Nullable<int> locationIntersectionTypeId { get; set; }
        public string LocationName { get; set; }
        public string Description { get; set; }
        public Nullable<int> GeoLEOId { get; set; }
        public Nullable<int> GeoLocationSubDivisionId { get; set; }
        public Nullable<int> GeoCountryId { get; set; }
        public Nullable<int> GeoCityId { get; set; }
        public Nullable<int> GeoCountyId { get; set; }
        public Nullable<int> GeoZipId { get; set; }
        public Nullable<int> GeoStateId { get; set; }
        public Nullable<int> GeoCensusTractId { get; set; }
        public Nullable<int> LocationStreetCategoryId { get; set; }
        public Nullable<int> LocationStreetDirectionPrefixId { get; set; }
        public Nullable<int> LocationStreetDirectionSuffixId { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string StreetExtension { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PostalCode { get; set; }
        public string PostalCodeExtension { get; set; }
        public string CrossStreet { get; set; }
        public string HighwayPosition { get; set; }
        public System.Data.Entity.Spatial.DbGeometry GeoPoint { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Boundry { get; set; }
        public string Unit { get; set; }
        public string Floor { get; set; }
        public string PostOfficeBox { get; set; }
        public Nullable<double> AltitudeAGL { get; set; }
        public Nullable<double> AltitudeMSL { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string OrgAddress1 { get; set; }
        public string OrgAddress2 { get; set; }
        public string OrgAddress3 { get; set; }
        public string OrgStateCode { get; set; }
        public string OrgCountry { get; set; }
        public string OrgConty { get; set; }
        public string OrgCity { get; set; }
        public string OrgZip { get; set; }
        public string OrgLat { get; set; }
        public string OrgLong { get; set; }
        public Nullable<bool> OrgLeoProcessed { get; set; }
        public Nullable<bool> OrgSubProcessed { get; set; }
        public Nullable<bool> OrgLocProcessed { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> RowStatusId { get; set; }
    
        public virtual ICollection<ActivityLocation> ActivityLocations { get; set; }
        public virtual Source Source { get; set; }
        public virtual LocationDatumDIM LocationDatumDIM { get; set; }
        public virtual LocationCategoryDIM LocationCategoryDIM { get; set; }
    }
}
