//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewCorrelationRule
    {
        public NewCorrelationRule()
        {
            this.CorrelationViolationDetails = new HashSet<CorrelationViolationDetail>();
            this.CorrelationMessagesLogs = new HashSet<CorrelationMessagesLog>();
            this.ReportDangerous = new HashSet<ReportDangerou>();
        }
    
        public long BusinessRuleId { get; set; }
        public string RuleName { get; set; }
        public int RulePriority { get; set; }
        public int IntervalPeriod { get; set; }
        public Nullable<int> LocationDetailsId { get; set; }
        public Nullable<int> VehicleDetailsId { get; set; }
        public Nullable<int> DriverDetailsId { get; set; }
        public int TimeDetailsId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int NumberOfOccur { get; set; }
    
        public virtual CorrelationDriverDetail CorrelationDriverDetail { get; set; }
        public virtual ICollection<CorrelationViolationDetail> CorrelationViolationDetails { get; set; }
        public virtual Region Region { get; set; }
        public virtual TimeDetail TimeDetail { get; set; }
        public virtual VehicleDetail VehicleDetail { get; set; }
        public virtual ICollection<CorrelationMessagesLog> CorrelationMessagesLogs { get; set; }
        public virtual ICollection<ReportDangerou> ReportDangerous { get; set; }
    }
}
