//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public long NotificationLogId { get; set; }
        public int OldStatus { get; set; }
        public int NewStatus { get; set; }
        public int UserId { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public long NotificationId { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual NotificationStatu NotificationStatu { get; set; }
        public virtual NotificationStatu NotificationStatu1 { get; set; }
        public virtual User User { get; set; }
    }
}
