//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficersLastLocationsView
    {
        public int OfficerLastLocationId { get; set; }
        public int OfficerId { get; set; }
        public int Speed { get; set; }
        public double Latitude { get; set; }
        public double Longitde { get; set; }
        public double Altitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public System.DateTime LocationDate { get; set; }
        public double OfficerHeartPulse { get; set; }
        public bool IsNoticed { get; set; }
        public string OfficerName { get; set; }
        public string OfficerCode { get; set; }
        public string CameraURL { get; set; }
    }
}
