//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficerTaskStatus
    {
        public long OfficerTaskStatusId { get; set; }
        public Nullable<long> OfficerTaskId { get; set; }
        public Nullable<int> TaskStatusId { get; set; }
        public Nullable<System.DateTime> StatusUpdateDate { get; set; }
        public string Notes { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public Nullable<bool> IsNoticed { get; set; }
    
        public virtual OfficerTask OfficerTask { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
    }
}
