//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficerTask
    {
        public OfficerTask()
        {
            this.OfficerTaskStatus = new HashSet<OfficerTaskStatus>();
        }
    
        public long OfficerTaskId { get; set; }
        public string OfficerMilitaryId { get; set; }
        public string TaskMessage { get; set; }
        public Nullable<System.DateTime> TaskTime { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsNoticed { get; set; }
    
        public virtual User Users { get; set; }
        public virtual ICollection<OfficerTaskStatus> OfficerTaskStatus { get; set; }
    }
}
