//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Officer
    {
        public Officer()
        {
            this.OfficersLastLocations = new HashSet<OfficersLastLocation>();
        }
    
        public int OfficerId { get; set; }
        public string OfficerName { get; set; }
        public string OfficerCode { get; set; }
        public string CameraURL { get; set; }
    
        public virtual ICollection<OfficersLastLocation> OfficersLastLocations { get; set; }
    }
}
