//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.PersonEducations = new HashSet<PersonEducation>();
        }
    
        public long OrganizationId { get; set; }
        public Nullable<System.Guid> OrganizationGuid { get; set; }
        public string OriginalIdent { get; set; }
        public long SourceId { get; set; }
        public Nullable<int> OrganizationCategoryId { get; set; }
        public Nullable<int> OrganizationStatusId { get; set; }
        public string Name { get; set; }
        public string DoingBusinessAs { get; set; }
        public string Description { get; set; }
        public string AbbreviationText { get; set; }
        public string IMONumber { get; set; }
        public Nullable<System.DateTime> EstablishedDateTime { get; set; }
        public Nullable<System.DateTime> TerminationDateTime { get; set; }
        public Nullable<bool> IncorporatedIndicator { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> RowStatusId { get; set; }
    
        public virtual Source Source { get; set; }
        public virtual ICollection<PersonEducation> PersonEducations { get; set; }
    }
}
