//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterDiminsions
    {
        public ParameterDiminsions()
        {
            this.AutomaticReportDiminsion = new HashSet<AutomaticReportDiminsion>();
        }
    
        public int DiminsionId { get; set; }
        public string Name { get; set; }
        public string FieldName { get; set; }
        public bool IsOneValue { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<AutomaticReportDiminsion> AutomaticReportDiminsion { get; set; }
    }
}
