//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patrol
    {
        public Patrol()
        {
            this.IncidentDispatches = new HashSet<IncidentDispatch>();
        }
    
        public long PatrolId { get; set; }
        public string PatrolCode { get; set; }
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public string PatrolPlateNo { get; set; }
        public System.Guid PatrolOriginalId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public byte[] PatrolImage { get; set; }
        public string OfficerName { get; set; }
        public Nullable<bool> IsPatrol { get; set; }
        public Nullable<long> CurrentTaskId { get; set; }
        public Nullable<bool> IsInTFM { get; set; }
    
        public virtual ICollection<IncidentDispatch> IncidentDispatches { get; set; }
    }
}
