//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatrolLastLocation
    {
        public long PatrolLatLocationId { get; set; }
        public long PatrolId { get; set; }
        public string PatrolCode { get; set; }
        public int Speed { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public double Altitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public System.DateTime LocationDate { get; set; }
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public bool IsNoticed { get; set; }
        public Nullable<bool> IsPatrol { get; set; }
    }
}
