//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDriverLicense
    {
        public long PersonDriverLicenseId { get; set; }
        public Nullable<System.Guid> PersonDriverLicenseGuid { get; set; }
        public string PersonDriverLicenseDescription { get; set; }
        public long PersonId { get; set; }
        public Nullable<System.Guid> PersonGuid { get; set; }
        public long SourceId { get; set; }
        public Nullable<long> DriverLicenseImageId { get; set; }
        public Nullable<System.Guid> DriverLicenseImageGuid { get; set; }
        public Nullable<int> DriverLicensePermitStatusId { get; set; }
        public Nullable<int> DriverLicenseCommericalClassId { get; set; }
        public Nullable<int> DriverLicenseCivilianClassId { get; set; }
        public Nullable<int> IdentificationAuthorityId { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> ExpirationYear { get; set; }
        public string Identification { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> EffectiveYear { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> PersonDrivingInsCoverageCategoryId { get; set; }
        public Nullable<int> PersonDrivingInsuranceStatusId { get; set; }
        public Nullable<int> RowStatusId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Source Source { get; set; }
    }
}
