//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.ActivityPersons = new HashSet<ActivityPerson>();
            this.PersonEducations = new HashSet<PersonEducation>();
            this.PersonDriverLicenses = new HashSet<PersonDriverLicense>();
        }
    
        public long PersonId { get; set; }
        public Nullable<System.Guid> PersonGuid { get; set; }
        public string Description { get; set; }
        public string OriginalIdent { get; set; }
        public long SourceId { get; set; }
        public Nullable<int> PersonStatusId { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Moniker { get; set; }
        public string Suffix { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> PersonCategoryId { get; set; }
        public Nullable<int> PersonGenderId { get; set; }
        public Nullable<int> RowStatusId { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual ICollection<ActivityPerson> ActivityPersons { get; set; }
        public virtual Source Source { get; set; }
        public virtual PersonGenderDIM PersonGenderDIM { get; set; }
        public virtual ICollection<PersonEducation> PersonEducations { get; set; }
        public virtual ICollection<PersonDriverLicense> PersonDriverLicenses { get; set; }
        public virtual PersonCategoryDIM PersonCategoryDIM { get; set; }
    }
}
