//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.NewCorrelationRules = new HashSet<NewCorrelationRule>();
        }
    
        public int RegionId { get; set; }
        public string RegionName { get; set; }
        public int RegionTypeId { get; set; }
        public string RegionPoints { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<NewCorrelationRule> NewCorrelationRules { get; set; }
    }
}
