//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDangerou
    {
        public long ReportDangerousId { get; set; }
        public Nullable<long> SupervisorNotificationId { get; set; }
        public string NotificationText { get; set; }
        public string PlateNumber { get; set; }
        public string PlateKind { get; set; }
        public string PlateColor { get; set; }
        public string PlateAuthority { get; set; }
        public Nullable<long> BusinessRuleId { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lon { get; set; }
        public string MediaURL { get; set; }
        public Nullable<int> MediaType { get; set; }
    
        public virtual SupervisorNotification SupervisorNotification { get; set; }
        public virtual NewCorrelationRule NewCorrelationRule { get; set; }
    }
}
