//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSchedule
    {
        public ReportSchedule()
        {
            this.AutomaticReports = new HashSet<AutomaticReports>();
        }
    
        public int ScheduleId { get; set; }
        public int ScheduleTypeId { get; set; }
        public string ScheduleValues { get; set; }
        public int SendHour { get; set; }
    
        public virtual ICollection<AutomaticReports> AutomaticReports { get; set; }
    }
}
