//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleFeature
    {
        public int RoleFeatureId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> FeatureId { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
