//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCallDriver
    {
        public ServiceCallDriver()
        {
            this.ActivityPersons = new HashSet<ActivityPersonView>();
        }
    
        public long PersonId { get; set; }
        public string Description { get; set; }
        public string OriginalIdent { get; set; }
        public string SourceName { get; set; }
        public string PersonStatusCode { get; set; }
        public string PersonStatusDescription { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Moniker { get; set; }
        public string Suffix { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> PersonCategoryId { get; set; }
        public string PersonGenderCode { get; set; }
        public string PersonGenderDescription { get; set; }
        public string RowStatusCode { get; set; }
        public string RowStatusDescription { get; set; }
        public string DriverNationalityCode { get; set; }
        public string DriverNationalityDescription { get; set; }
        public string DriverLicenceSourceCode { get; set; }
        public string DriverLicenceSourceDescription { get; set; }
        public string DriverLicenceTypeCode { get; set; }
        public string DriverLicenceTypeDescription { get; set; }
    
        public virtual ICollection<ActivityPersonView> ActivityPersons { get; set; }
    }
}
