//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class server
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public server()
        {
            this.elrocs = new HashSet<elroc>();
        }
    
        public int no { get; set; }
        public string name { get; set; }
        public Nullable<int> location_code { get; set; }
        public string alias { get; set; }
        public Nullable<long> link_id { get; set; }
        public string ip_address { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<int> radar_serial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<elroc> elrocs { get; set; }
    }
}
