//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public Source()
        {
            this.Activities = new HashSet<Activity>();
            this.ItemRegistrations = new HashSet<ItemRegistration>();
            this.Items = new HashSet<Item>();
            this.ActivityLocations = new HashSet<ActivityLocation>();
            this.ActivityPersons = new HashSet<ActivityPerson>();
            this.Locations = new HashSet<Location>();
            this.People = new HashSet<Person>();
            this.PersonEducations = new HashSet<PersonEducation>();
            this.PersonDriverLicenses = new HashSet<PersonDriverLicense>();
            this.Organizations = new HashSet<Organization>();
        }
    
        public long SourceId { get; set; }
        public System.Guid SourceGuid { get; set; }
        public int SourceCategoryId { get; set; }
        public int SourcePolicyId { get; set; }
        public string SourceName { get; set; }
        public string Description { get; set; }
        public Nullable<int> RetentionPeriodDays { get; set; }
        public Nullable<bool> RetentionPeriodEnforcedIndicator { get; set; }
        public Nullable<System.DateTime> CreateDateTimeStamp { get; set; }
        public Nullable<System.DateTime> ModifiedDateTimeStamp { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> RowStatusId { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<ItemRegistration> ItemRegistrations { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<ActivityLocation> ActivityLocations { get; set; }
        public virtual ICollection<ActivityPerson> ActivityPersons { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<PersonEducation> PersonEducations { get; set; }
        public virtual ICollection<PersonDriverLicense> PersonDriverLicenses { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
    }
}
