//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.iPatrolDutiesUsers = new HashSet<iPatrolDutiesUser>();
            this.iPatrolFilesSubmittedByUsers = new HashSet<iPatrolFilesSubmittedByUser>();
            this.OfficersAttendances = new HashSet<OfficersAttendance>();
            this.Incidents = new HashSet<TFMIncident>();
        }
    
        public System.Guid ID { get; set; }
        public string FirstName { get; set; }
        public string descr { get; set; }
        public string code { get; set; }
        public System.Guid subID { get; set; }
        public Nullable<System.Guid> staffRoleID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string image { get; set; }
        public bool isAllocated { get; set; }
        public string personalID { get; set; }
        public Nullable<System.Guid> AllocatedBranch { get; set; }
        public Nullable<System.Guid> AllocatedLandmark { get; set; }
        public Nullable<System.Guid> status { get; set; }
        public Nullable<System.Guid> employmentType { get; set; }
        public Nullable<System.DateTime> employmentDate { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string mobileNumber { get; set; }
        public Nullable<bool> MonitorFlag { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<double> LaborRate { get; set; }
        public string LisenceNumber { get; set; }
        public Nullable<System.DateTime> LisenceIssueDate { get; set; }
        public Nullable<System.DateTime> LisenceExpiryDate { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<System.DateTime> InsuranceIssueDate { get; set; }
        public Nullable<System.Guid> InsuranceCompanyID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string EmergencyContactName1 { get; set; }
        public string EmergencyContactName2 { get; set; }
        public string EmergencyContactPhone1 { get; set; }
        public string EmergencyContactPhone2 { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string Email { get; set; }
        public string StaffRoleName { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iPatrolDutiesUser> iPatrolDutiesUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iPatrolFilesSubmittedByUser> iPatrolFilesSubmittedByUsers { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficersAttendance> OfficersAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFMIncident> Incidents { get; set; }
    }
}
