//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupervisorNotification
    {
        public SupervisorNotification()
        {
            this.ReportDangerous = new HashSet<ReportDangerou>();
            this.SupervisorNotification1 = new HashSet<SupervisorNotification>();
        }
    
        public long SupervisorNotificationId { get; set; }
        public Nullable<System.DateTime> NotificationTime { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public Nullable<bool> IsNoticed { get; set; }
        public Nullable<long> ResponseToId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual ICollection<ReportDangerou> ReportDangerous { get; set; }
        public virtual ICollection<SupervisorNotification> SupervisorNotification1 { get; set; }
        public virtual SupervisorNotification SupervisorNotification2 { get; set; }
    }
}
