//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStatus
    {
        public TaskStatus()
        {
            this.OfficerTaskStatus = new HashSet<OfficerTaskStatus>();
        }
    
        public int TaskStatusId { get; set; }
        public string TaskStatusNameAr { get; set; }
        public string TaskStatusNameEn { get; set; }
        public Nullable<bool> AvailableToOfficer { get; set; }
    
        public virtual ICollection<OfficerTaskStatus> OfficerTaskStatus { get; set; }
    }
}
