//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeDetail
    {
        public TimeDetail()
        {
            this.NewCorrelationRules = new HashSet<NewCorrelationRule>();
        }
    
        public int TimeDetailsId { get; set; }
        public int TimeType { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string WeekDays { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
        public Nullable<System.TimeSpan> ToTime { get; set; }
    
        public virtual ICollection<NewCorrelationRule> NewCorrelationRules { get; set; }
    }
}
