//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transporter()
        {
            this.Incidents = new HashSet<TFMIncident>();
            this.iPatrolDuties = new HashSet<iPatrolDuty>();
            this.OfficersAttendances = new HashSet<OfficersAttendance>();
        }
    
        public System.Guid ID { get; set; }
        public string code { get; set; }
        public string plateNo { get; set; }
        public string transporterTypeName { get; set; }
        public Nullable<System.Guid> transporterType { get; set; }
        public Nullable<System.Guid> branch { get; set; }
        public Nullable<System.Guid> landmark { get; set; }
        public double maxSpeed { get; set; }
        public decimal literPerKm { get; set; }
        public Nullable<double> currentMileage { get; set; }
        public string image { get; set; }
        public string color { get; set; }
        public Nullable<System.Guid> transporterBrand { get; set; }
        public Nullable<System.Guid> transporterProductionYear { get; set; }
        public Nullable<System.Guid> transporterManufacturer { get; set; }
        public Nullable<bool> deviceType { get; set; }
        public string SIMCardNo { get; set; }
        public string providerName { get; set; }
        public string deviceCode { get; set; }
        public string licenseNo { get; set; }
        public Nullable<System.DateTime> licenseExpiryDate { get; set; }
        public string chassisNo { get; set; }
        public string engineNo { get; set; }
        public Nullable<System.DateTime> entranceDate { get; set; }
        public string insuranceNo { get; set; }
        public string insuredBy { get; set; }
        public Nullable<System.DateTime> insuranceStartDate { get; set; }
        public Nullable<System.DateTime> insuranceEndDate { get; set; }
        public Nullable<System.Guid> supplier { get; set; }
        public Nullable<bool> isMonitored { get; set; }
        public System.Guid SubID { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public string SupplierName { get; set; }
        public string LisenceImage { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<double> HourRate { get; set; }
        public Nullable<decimal> FuelCost { get; set; }
        public Nullable<decimal> TempSensorMinValue { get; set; }
        public Nullable<decimal> TempSensorMaxValue { get; set; }
        public Nullable<System.Guid> DeviceID { get; set; }
        public Nullable<System.DateTime> NextExaminationDate { get; set; }
        public string CurrentSituationNote { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public Nullable<double> FuelCalibrationConst_A { get; set; }
        public Nullable<double> FuelCalibrationConst_B { get; set; }
        public Nullable<double> FuelCalibrationConst_C { get; set; }
        public Nullable<double> FuelCalibrationConst_D { get; set; }
        public Nullable<double> TotalWorkingHours { get; set; }
        public Nullable<double> TankCapacity { get; set; }
        public Nullable<double> AnalogInputOneMin { get; set; }
        public Nullable<double> AnalogInputOneMax { get; set; }
        public Nullable<double> AnalogInputTwoMin { get; set; }
        public Nullable<double> AnalogInputTwoMax { get; set; }
        public Nullable<double> AnalogInputThreeMin { get; set; }
        public Nullable<double> AnalogInputThreeMax { get; set; }
        public Nullable<double> AnalogInputFourMin { get; set; }
        public Nullable<double> AnalogInputFourMax { get; set; }
        public Nullable<System.Guid> OldPlace { get; set; }
        public Nullable<System.DateTime> currentMileageLastModificationDate { get; set; }
        public string MDTDeviceCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFMIncident> Incidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iPatrolDuty> iPatrolDuties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficersAttendance> OfficersAttendances { get; set; }
    }
}
