//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public UserRole()
        {
            this.Users = new HashSet<User>();
            this.RoleFeatures = new HashSet<RoleFeature>();
        }
    
        public int UserRoleId { get; set; }
        public string UserRoleName { get; set; }
        public string UserRoleDescriptionAr { get; set; }
        public string UserRoleDescriptionEn { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<RoleFeature> RoleFeatures { get; set; }
    }
}
