//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail
    {
        public VehicleDetail()
        {
            this.NewCorrelationRules = new HashSet<NewCorrelationRule>();
        }
    
        public int VehicleDetailsId { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public Nullable<int> VehicleBrandUTSId { get; set; }
        public Nullable<int> VehicleModelYear { get; set; }
    
        public virtual ICollection<NewCorrelationRule> NewCorrelationRules { get; set; }
    }
}
