//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleMake
    {
        public int VEM_ID { get; set; }
        public Nullable<int> VEM_CODE { get; set; }
        public string VEM_DESC_AR { get; set; }
        public string VEM_DESC_EN { get; set; }
    }
}
