//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.ClassLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViolationNotification
    {
        public long ViolationNotificationId { get; set; }
        public long LPRId { get; set; }
        public string AssetId { get; set; }
        public string AssetCode { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocation { get; set; }
        public double Altitude { get; set; }
        public string LocationCode { get; set; }
        public int ViolationTypeId { get; set; }
        public string ViolationTypeName { get; set; }
        public System.DateTime DateTaken { get; set; }
        public int SpeedLimit { get; set; }
        public int MesuredSpeed { get; set; }
        public int CapturedSpeed { get; set; }
        public string PlateNumber { get; set; }
        public int VehicleTypeId { get; set; }
        public string VehicleTypeName { get; set; }
        public string PlateColorName { get; set; }
        public string PlateSourceName { get; set; }
        public string PlateTypeName { get; set; }
        public string PlateKindName { get; set; }
        public int Direction { get; set; }
        public string DirectionName { get; set; }
        public int LaneNo { get; set; }
        public int SourceId { get; set; }
        public string SourceName { get; set; }
        public int ViolationStatusId { get; set; }
        public string ViolationStatusName { get; set; }
        public bool IsNoticed { get; set; }
        public bool IsCritical { get; set; }
        public Nullable<long> NotificationId { get; set; }
    
        public virtual ViolationNotification ViolationNotification1 { get; set; }
        public virtual ViolationNotification ViolationNotification2 { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
