//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.WPFControlLibrary.NavigationBar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STC.Projects.WPFControlLibrary.NavigationBar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents.
        /// </summary>
        public static string strAccident {
            get {
                return ResourceManager.GetString("strAccident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string strAdmin {
            get {
                return ResourceManager.GetString("strAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Message.
        /// </summary>
        public static string strAdminMessage {
            get {
                return ResourceManager.GetString("strAdminMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string strAssets {
            get {
                return ResourceManager.GetString("strAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Violator.
        /// </summary>
        public static string strDangerousViolator {
            get {
                return ResourceManager.GetString("strDangerousViolator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        public static string strDashboard {
            get {
                return ResourceManager.GetString("strDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents KPI.
        /// </summary>
        public static string strIncidentsKPI {
            get {
                return ResourceManager.GetString("strIncidentsKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI Admin.
        /// </summary>
        public static string strKPIAdmin {
            get {
                return ResourceManager.GetString("strKPIAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string strLive {
            get {
                return ResourceManager.GetString("strLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string strLogOut {
            get {
                return ResourceManager.GetString("strLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrols.
        /// </summary>
        public static string strPatrol {
            get {
                return ResourceManager.GetString("strPatrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic.
        /// </summary>
        public static string strTraffic {
            get {
                return ResourceManager.GetString("strTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Permissions.
        /// </summary>
        public static string strTruckPermissions {
            get {
                return ResourceManager.GetString("strTruckPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations.
        /// </summary>
        public static string strViolation {
            get {
                return ResourceManager.GetString("strViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations KPI.
        /// </summary>
        public static string strViolationKPI {
            get {
                return ResourceManager.GetString("strViolationKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Zones.
        /// </summary>
        public static string strWorkZones {
            get {
                return ResourceManager.GetString("strWorkZones", resourceCulture);
            }
        }
    }
}
