//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.WCF.ServiceLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.09")]
        public decimal WantedCarRadius {
            get {
                return ((decimal)(this["WantedCarRadius"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.2:8080/cms/PerspectiveMgtAPIImpl")]
        public string STC_Projects_WCF_ServiceLayer_BarcoWebReference_PerspectiveMgtAPI {
            get {
                return ((string)(this["STC_Projects_WCF_ServiceLayer_BarcoWebReference_PerspectiveMgtAPI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fugrows.manufaktura.rs:82/permission/HeavyLoadPermits.asmx")]
        public string STC_Projects_WCF_ServiceLayer_HeavyLoadRef_HeavyLoadPermits {
            get {
                return ((string)(this["STC_Projects_WCF_ServiceLayer_HeavyLoadRef_HeavyLoadPermits"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fugrows.manufaktura.rs:82/permission/ConstructionPermits.asmx")]
        public string STC_Projects_WCF_ServiceLayer_ConstructionPermit_ConstructionPermits {
            get {
                return ((string)(this["STC_Projects_WCF_ServiceLayer_ConstructionPermit_ConstructionPermits"]));
            }
        }
    }
}
