//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STC.Projects.WPFControlLibrary.SOPBox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STC.Projects.WPFControlLibrary.SOPBox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string EtaUnit {
            get {
                return ResourceManager.GetString("EtaUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        public static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidents.
        /// </summary>
        public static string strAccidents {
            get {
                return ResourceManager.GetString("strAccidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement Percentage.
        /// </summary>
        public static string strAchievementPercentage {
            get {
                return ResourceManager.GetString("strAchievementPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string strAction {
            get {
                return ResourceManager.GetString("strAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Working Hours.
        /// </summary>
        public static string strActiveWorkingHours {
            get {
                return ResourceManager.GetString("strActiveWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Operation Room.
        /// </summary>
        public static string strAlertOperationRoom {
            get {
                return ResourceManager.GetString("strAlertOperationRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, want to Alert the Operation Room?.
        /// </summary>
        public static string strAlertOpRoomConfMsg {
            get {
                return ResourceManager.GetString("strAlertOpRoomConfMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Status :.
        /// </summary>
        public static string strAlertStatus {
            get {
                return ResourceManager.GetString("strAlertStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to approve?.
        /// </summary>
        public static string strApprovalConfirmation {
            get {
                return ResourceManager.GetString("strApprovalConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string strApprove {
            get {
                return ResourceManager.GetString("strApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Details.
        /// </summary>
        public static string strAssetDetails {
            get {
                return ResourceManager.GetString("strAssetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Name:.
        /// </summary>
        public static string strAssetName {
            get {
                return ResourceManager.GetString("strAssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string strAssets {
            get {
                return ResourceManager.GetString("strAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Status:.
        /// </summary>
        public static string strAssetStatus {
            get {
                return ResourceManager.GetString("strAssetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string strAssigned {
            get {
                return ResourceManager.GetString("strAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Patrol:.
        /// </summary>
        public static string strAssignedPatrol {
            get {
                return ResourceManager.GetString("strAssignedPatrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Speed :.
        /// </summary>
        public static string strAssignedSpeed {
            get {
                return ResourceManager.GetString("strAssignedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned VMS :.
        /// </summary>
        public static string strAssignedVMS {
            get {
                return ResourceManager.GetString("strAssignedVMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Response time:.
        /// </summary>
        public static string strAverageResponsetime {
            get {
                return ResourceManager.GetString("strAverageResponsetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back &gt;&gt;.
        /// </summary>
        public static string strBack {
            get {
                return ResourceManager.GetString("strBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Allocation Hub:.
        /// </summary>
        public static string strBasicAllocationHub {
            get {
                return ResourceManager.GetString("strBasicAllocationHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Informations.
        /// </summary>
        public static string strBasicInfo {
            get {
                return ResourceManager.GetString("strBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Pressure.
        /// </summary>
        public static string strBloodPressure {
            get {
                return ResourceManager.GetString("strBloodPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string strBrowseImage {
            get {
                return ResourceManager.GetString("strBrowseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Rule.
        /// </summary>
        public static string strBusinessRule {
            get {
                return ResourceManager.GetString("strBusinessRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string strCamera {
            get {
                return ResourceManager.GetString("strCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Details.
        /// </summary>
        public static string strCameraDetails {
            get {
                return ResourceManager.GetString("strCameraDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string strCapturedSpeed {
            get {
                return ResourceManager.GetString("strCapturedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Detail.
        /// </summary>
        public static string strCarDetails {
            get {
                return ResourceManager.GetString("strCarDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCTV Name :.
        /// </summary>
        public static string strCCTVName {
            get {
                return ResourceManager.GetString("strCCTVName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCTVs.
        /// </summary>
        public static string strCCTVs {
            get {
                return ResourceManager.GetString("strCCTVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCTV SerialNo :.
        /// </summary>
        public static string strCCTVSerialNo {
            get {
                return ResourceManager.GetString("strCCTVSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string strChange {
            get {
                return ResourceManager.GetString("strChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string strCode {
            get {
                return ResourceManager.GetString("strCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string strColor {
            get {
                return ResourceManager.GetString("strColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment :.
        /// </summary>
        public static string strComment {
            get {
                return ResourceManager.GetString("strComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string strComments {
            get {
                return ResourceManager.GetString("strComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string strConfirm {
            get {
                return ResourceManager.GetString("strConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string strCountry {
            get {
                return ResourceManager.GetString("strCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal Record.
        /// </summary>
        public static string strCriminalRecord {
            get {
                return ResourceManager.GetString("strCriminalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Message.
        /// </summary>
        public static string strCurrentMessage {
            get {
                return ResourceManager.GetString("strCurrentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Speed :.
        /// </summary>
        public static string strCurrentSpeed {
            get {
                return ResourceManager.GetString("strCurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time.
        /// </summary>
        public static string strCurrentTime {
            get {
                return ResourceManager.GetString("strCurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Vehicle.
        /// </summary>
        public static string strDangerousVehicleDetails {
            get {
                return ResourceManager.GetString("strDangerousVehicleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Violator.
        /// </summary>
        public static string strDangerousViolator {
            get {
                return ResourceManager.GetString("strDangerousViolator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        public static string strDate {
            get {
                return ResourceManager.GetString("strDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string strDirection {
            get {
                return ResourceManager.GetString("strDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task has been dispatched to the patrol.
        /// </summary>
        public static string strDispatchedPatrolConfirm {
            get {
                return ResourceManager.GetString("strDispatchedPatrolConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatching Time:.
        /// </summary>
        public static string strDispatchingTime {
            get {
                return ResourceManager.GetString("strDispatchingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch Patrol.
        /// </summary>
        public static string strDispatchPatrol {
            get {
                return ResourceManager.GetString("strDispatchPatrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to dispatch the patrol ?.
        /// </summary>
        public static string strDispatchPatrolConfirmation {
            get {
                return ResourceManager.GetString("strDispatchPatrolConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string strDone {
            get {
                return ResourceManager.GetString("strDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Age.
        /// </summary>
        public static string strDriverAge {
            get {
                return ResourceManager.GetString("strDriverAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Details.
        /// </summary>
        public static string strEditDetails {
            get {
                return ResourceManager.GetString("strEditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string strEnd {
            get {
                return ResourceManager.GetString("strEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all steps are checked . Are you sure you want to finish the SOP?.
        /// </summary>
        public static string strEndSOP {
            get {
                return ResourceManager.GetString("strEndSOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string strEndTime {
            get {
                return ResourceManager.GetString("strEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string strFacebook {
            get {
                return ResourceManager.GetString("strFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False Detection.
        /// </summary>
        public static string strFalseDetection {
            get {
                return ResourceManager.GetString("strFalseDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health KPIs.
        /// </summary>
        public static string strHealthKPIs {
            get {
                return ResourceManager.GetString("strHealthKPIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Pluse Rate.
        /// </summary>
        public static string strHeartPluseRate {
            get {
                return ResourceManager.GetString("strHeartPluseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Img.
        /// </summary>
        public static string strImage {
            get {
                return ResourceManager.GetString("strImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Img.
        /// </summary>
        public static string strImage1 {
            get {
                return ResourceManager.GetString("strImage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        public static string strincident {
            get {
                return ResourceManager.GetString("strincident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Address:.
        /// </summary>
        public static string strIncidentAddress {
            get {
                return ResourceManager.GetString("strIncidentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Finished time:.
        /// </summary>
        public static string strIncidentFinishedtime {
            get {
                return ResourceManager.GetString("strIncidentFinishedtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Status:.
        /// </summary>
        public static string strIncidentStatus {
            get {
                return ResourceManager.GetString("strIncidentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Time:.
        /// </summary>
        public static string strIncidentTime {
            get {
                return ResourceManager.GetString("strIncidentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Type:.
        /// </summary>
        public static string strIncidentType {
            get {
                return ResourceManager.GetString("strIncidentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string strInfo {
            get {
                return ResourceManager.GetString("strInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string strIssue {
            get {
                return ResourceManager.GetString("strIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue/Fine.
        /// </summary>
        public static string strIssueOrFine {
            get {
                return ResourceManager.GetString("strIssueOrFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string strKPI {
            get {
                return ResourceManager.GetString("strKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Incident time:.
        /// </summary>
        public static string strLastIncidenttime {
            get {
                return ResourceManager.GetString("strLastIncidenttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Known Location.
        /// </summary>
        public static string strLastKnownLocation {
            get {
                return ResourceManager.GetString("strLastKnownLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Response Time:.
        /// </summary>
        public static string strLastResponseTime {
            get {
                return ResourceManager.GetString("strLastResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Speed Limit Modification Details :.
        /// </summary>
        public static string strLastSpeedLimitModificationDetails {
            get {
                return ResourceManager.GetString("strLastSpeedLimitModificationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Visibility Range :.
        /// </summary>
        public static string strLastVisibilityRange {
            get {
                return ResourceManager.GetString("strLastVisibilityRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last VMS Modification Details :.
        /// </summary>
        public static string strLastVMSModificationDetails {
            get {
                return ResourceManager.GetString("strLastVMSModificationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Expiry Date.
        /// </summary>
        public static string strLicenceExpiryDate {
            get {
                return ResourceManager.GetString("strLicenceExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Number.
        /// </summary>
        public static string strLicenceNum {
            get {
                return ResourceManager.GetString("strLicenceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Expiry Date.
        /// </summary>
        public static string strLicenseExpiryDate {
            get {
                return ResourceManager.GetString("strLicenseExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location :.
        /// </summary>
        public static string strLocation {
            get {
                return ResourceManager.GetString("strLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string strLocation1 {
            get {
                return ResourceManager.GetString("strLocation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string strLogout {
            get {
                return ResourceManager.GetString("strLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string strManufacturer {
            get {
                return ResourceManager.GetString("strManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture Year.
        /// </summary>
        public static string strManufactureYear {
            get {
                return ResourceManager.GetString("strManufactureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string strMessage {
            get {
                return ResourceManager.GetString("strMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mins 15.
        /// </summary>
        public static string strMins15 {
            get {
                return ResourceManager.GetString("strMins15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mins 30.
        /// </summary>
        public static string strMins30 {
            get {
                return ResourceManager.GetString("strMins30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mins 45.
        /// </summary>
        public static string strMins45 {
            get {
                return ResourceManager.GetString("strMins45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string strModel {
            get {
                return ResourceManager.GetString("strModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification Date/Time :.
        /// </summary>
        public static string strModificationDateTime {
            get {
                return ResourceManager.GetString("strModificationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By :.
        /// </summary>
        public static string strModifiedBy {
            get {
                return ResourceManager.GetString("strModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string strNationality {
            get {
                return ResourceManager.GetString("strNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCTV Nearby.
        /// </summary>
        public static string strNearbyCamera {
            get {
                return ResourceManager.GetString("strNearbyCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message :.
        /// </summary>
        public static string strNewMessage {
            get {
                return ResourceManager.GetString("strNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Speed Limit :.
        /// </summary>
        public static string strNewSpeedLimit {
            get {
                return ResourceManager.GetString("strNewSpeedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string strNext {
            get {
                return ResourceManager.GetString("strNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string strNotification {
            get {
                return ResourceManager.GetString("strNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Active hours:.
        /// </summary>
        public static string strNumofActivehours {
            get {
                return ResourceManager.GetString("strNumofActivehours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Incidents Handled:.
        /// </summary>
        public static string strNumofIncidentsHandled {
            get {
                return ResourceManager.GetString("strNumofIncidentsHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string strOff {
            get {
                return ResourceManager.GetString("strOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer Allocation.
        /// </summary>
        public static string strOfficerAllocation {
            get {
                return ResourceManager.GetString("strOfficerAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer Details.
        /// </summary>
        public static string strOfficerDetails {
            get {
                return ResourceManager.GetString("strOfficerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer Name:.
        /// </summary>
        public static string strOfficerName {
            get {
                return ResourceManager.GetString("strOfficerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer Phone Numbers:.
        /// </summary>
        public static string strOfficerPhoneNumbers {
            get {
                return ResourceManager.GetString("strOfficerPhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officers.
        /// </summary>
        public static string strOfficers {
            get {
                return ResourceManager.GetString("strOfficers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officers Military Number:.
        /// </summary>
        public static string strOfficersMilitaryNumber {
            get {
                return ResourceManager.GetString("strOfficersMilitaryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officers names:.
        /// </summary>
        public static string strOfficersnames {
            get {
                return ResourceManager.GetString("strOfficersnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string strOK {
            get {
                return ResourceManager.GetString("strOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string strOn {
            get {
                return ResourceManager.GetString("strOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Age.
        /// </summary>
        public static string strOwnerAge {
            get {
                return ResourceManager.GetString("strOwnerAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Mobile Number.
        /// </summary>
        public static string strOwnerMobileNum {
            get {
                return ResourceManager.GetString("strOwnerMobileNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Mobile Number.
        /// </summary>
        public static string strOwnerMobileNum1 {
            get {
                return ResourceManager.GetString("strOwnerMobileNum1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string strOwnerName {
            get {
                return ResourceManager.GetString("strOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Nationality.
        /// </summary>
        public static string strOwnerNationality {
            get {
                return ResourceManager.GetString("strOwnerNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passing Code.
        /// </summary>
        public static string strPassingCode {
            get {
                return ResourceManager.GetString("strPassingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol Arrived:.
        /// </summary>
        public static string strPatrolArrived {
            get {
                return ResourceManager.GetString("strPatrolArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Patrol is already assigned to the same violation.
        /// </summary>
        public static string strPatrolAssignment {
            get {
                return ResourceManager.GetString("strPatrolAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol Code :.
        /// </summary>
        public static string strPatrolCode {
            get {
                return ResourceManager.GetString("strPatrolCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol Details.
        /// </summary>
        public static string strPatrolDetails {
            get {
                return ResourceManager.GetString("strPatrolDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol ID:.
        /// </summary>
        public static string strPatrolID {
            get {
                return ResourceManager.GetString("strPatrolID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol Performance.
        /// </summary>
        public static string strPatrolPerformance {
            get {
                return ResourceManager.GetString("strPatrolPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol Plate No.
        /// </summary>
        public static string strPatrolPlateNo {
            get {
                return ResourceManager.GetString("strPatrolPlateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrols.
        /// </summary>
        public static string strPatrols {
            get {
                return ResourceManager.GetString("strPatrols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Code.
        /// </summary>
        public static string strPlateCode {
            get {
                return ResourceManager.GetString("strPlateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Kind.
        /// </summary>
        public static string strPlateKind {
            get {
                return ResourceManager.GetString("strPlateKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Number.
        /// </summary>
        public static string strPlateNum {
            get {
                return ResourceManager.GetString("strPlateNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Source.
        /// </summary>
        public static string strPlateSource {
            get {
                return ResourceManager.GetString("strPlateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Type.
        /// </summary>
        public static string strPlateType {
            get {
                return ResourceManager.GetString("strPlateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your post has been shared successfully.
        /// </summary>
        public static string strPostSent {
            get {
                return ResourceManager.GetString("strPostSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string strPublish {
            get {
                return ResourceManager.GetString("strPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Story.
        /// </summary>
        public static string strPublishStory {
            get {
                return ResourceManager.GetString("strPublishStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar Details.
        /// </summary>
        public static string strRadarDetails {
            get {
                return ResourceManager.GetString("strRadarDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar Name.
        /// </summary>
        public static string strRadarName {
            get {
                return ResourceManager.GetString("strRadarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar SerialNo:.
        /// </summary>
        public static string strRadarSerialNo {
            get {
                return ResourceManager.GetString("strRadarSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rador Code.
        /// </summary>
        public static string strRadorCode {
            get {
                return ResourceManager.GetString("strRadorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string strReason {
            get {
                return ResourceManager.GetString("strReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string strReject {
            get {
                return ResourceManager.GetString("strReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Reject?.
        /// </summary>
        public static string strRejectionConfirmation {
            get {
                return ResourceManager.GetString("strRejectionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Dangerous Violators List.
        /// </summary>
        public static string strRemoveFromDangViolator {
            get {
                return ResourceManager.GetString("strRemoveFromDangViolator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT.
        /// </summary>
        public static string strReportBig {
            get {
                return ResourceManager.GetString("strReportBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Dangerous Violator.
        /// </summary>
        public static string strReportDangerousViolator {
            get {
                return ResourceManager.GetString("strReportDangerousViolator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported By :.
        /// </summary>
        public static string strReportedBy {
            get {
                return ResourceManager.GetString("strReportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported Dangerous :.
        /// </summary>
        public static string strReportedDangerous {
            get {
                return ResourceManager.GetString("strReportedDangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report To UTS.
        /// </summary>
        public static string strReportToUTS {
            get {
                return ResourceManager.GetString("strReportToUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved in UTS.
        /// </summary>
        public static string strSavedinUTS {
            get {
                return ResourceManager.GetString("strSavedinUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        public static string strSEARCHbigLetter {
            get {
                return ResourceManager.GetString("strSEARCHbigLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Dangerous Violator.
        /// </summary>
        public static string strSearchDangerousViolator {
            get {
                return ResourceManager.GetString("strSearchDangerousViolator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Now.
        /// </summary>
        public static string strSearchNow {
            get {
                return ResourceManager.GetString("strSearchNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string strSelect {
            get {
                return ResourceManager.GetString("strSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the prefered social site.
        /// </summary>
        public static string strSelectSocialService {
            get {
                return ResourceManager.GetString("strSelectSocialService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string strSend {
            get {
                return ResourceManager.GetString("strSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request to the Central Operation Room.
        /// </summary>
        public static string strSendRequestToSOP {
            get {
                return ResourceManager.GetString("strSendRequestToSOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string strSkip {
            get {
                return ResourceManager.GetString("strSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Tower Details.
        /// </summary>
        public static string strSmartTowerDetails {
            get {
                return ResourceManager.GetString("strSmartTowerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP List.
        /// </summary>
        public static string strSOPList {
            get {
                return ResourceManager.GetString("strSOPList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string strSource {
            get {
                return ResourceManager.GetString("strSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string strSpeedLimit {
            get {
                return ResourceManager.GetString("strSpeedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Speed Limit Saved.
        /// </summary>
        public static string strSpeedLimitSaved {
            get {
                return ResourceManager.GetString("strSpeedLimitSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string strStatus {
            get {
                return ResourceManager.GetString("strStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        public static string strSubmit {
            get {
                return ResourceManager.GetString("strSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string strTemperature {
            get {
                return ResourceManager.GetString("strTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string strTime {
            get {
                return ResourceManager.GetString("strTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tower Name :.
        /// </summary>
        public static string strTowerName {
            get {
                return ResourceManager.GetString("strTowerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tower SerialNo :.
        /// </summary>
        public static string strTowerSerialNo {
            get {
                return ResourceManager.GetString("strTowerSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track ID.
        /// </summary>
        public static string strTrackId {
            get {
                return ResourceManager.GetString("strTrackId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string strTwitter {
            get {
                return ResourceManager.GetString("strTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type :.
        /// </summary>
        public static string strType {
            get {
                return ResourceManager.GetString("strType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string strType1 {
            get {
                return ResourceManager.GetString("strType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users To Send.
        /// </summary>
        public static string strUsersToSend {
            get {
                return ResourceManager.GetString("strUsersToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string strValidate {
            get {
                return ResourceManager.GetString("strValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string strVehicleColor {
            get {
                return ResourceManager.GetString("strVehicleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Color.
        /// </summary>
        public static string strVehicleColor1 {
            get {
                return ResourceManager.GetString("strVehicleColor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEHICLE DETAILS.
        /// </summary>
        public static string strVehicleDetails {
            get {
                return ResourceManager.GetString("strVehicleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was this vehicle wanted before?.
        /// </summary>
        public static string strVehicleQuestion {
            get {
                return ResourceManager.GetString("strVehicleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string strVehicleType {
            get {
                return ResourceManager.GetString("strVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Violations Details.
        /// </summary>
        public static string strVehicleViolationsDetails {
            get {
                return ResourceManager.GetString("strVehicleViolationsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name:.
        /// </summary>
        public static string strVendorName {
            get {
                return ResourceManager.GetString("strVendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vid.
        /// </summary>
        public static string strVideo {
            get {
                return ResourceManager.GetString("strVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string strViewDetails {
            get {
                return ResourceManager.GetString("strViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string strViolationDateTime {
            get {
                return ResourceManager.GetString("strViolationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string strViolationDateTime1 {
            get {
                return ResourceManager.GetString("strViolationDateTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation Details.
        /// </summary>
        public static string strViolationDetails {
            get {
                return ResourceManager.GetString("strViolationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation / Detection Date &amp; Time.
        /// </summary>
        public static string strViolationDetectionDate {
            get {
                return ResourceManager.GetString("strViolationDetectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIOLATION EVIDENCE.
        /// </summary>
        public static string strViolationEvidence {
            get {
                return ResourceManager.GetString("strViolationEvidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string strViolationID {
            get {
                return ResourceManager.GetString("strViolationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations.
        /// </summary>
        public static string strViolations {
            get {
                return ResourceManager.GetString("strViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations by Types.
        /// </summary>
        public static string strViolationsbyTypes {
            get {
                return ResourceManager.GetString("strViolationsbyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations History.
        /// </summary>
        public static string strViolationsHistory {
            get {
                return ResourceManager.GetString("strViolationsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string strViolationType {
            get {
                return ResourceManager.GetString("strViolationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string strViolationType1 {
            get {
                return ResourceManager.GetString("strViolationType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation Type.
        /// </summary>
        public static string strViolnType {
            get {
                return ResourceManager.GetString("strViolnType", resourceCulture);
            }
        }
    }
}
